cisagov/crossfeed

backend/src/tasks/helpers/getAllDomains.ts, backend/src/tasks/test/helpers/getAllDomains.test.ts
The change to getAllDomains in #100 with queryBuilder actually ended up making that function always return an empty array. I've changed this function to just use `Domain.find` (which is simpler and seems to work better), and added tests for this function as well.
=> Fix getAllDomains

frontend/src/components/ServicesTable/ServicesTable.tsx
We currently show this even if the censys ipv4 results are empty (meaning, likely, that a scan has not gotten to this service yet). This is because, by default, `censysIpv4Results` is an empty object.
This PR fixes that to only show the "censys ipv4 results" section if there actually are results.
=> Don't show censys ipv4 results if no results are there

docs/workers.md
Remove the "fargate vs lambda" section as it is obsolete (we no longer support lambda scans).
=> Remove the "fargate vs lambda" section from worker docs

infrastructure/README.md
Add additional variables to terraform docs that need to be set in SSM before spinning up a new instance of Crossfeed.
=> Add initial required SSM variables to terraform docs

backend/src/api/scans.ts, backend/src/tasks/censysIpv4.ts, backend/src/tasks/test/scheduler.test.ts
The censys ipv4 scan has worked -- see https://staging.crossfeed.cyber.dhs.gov/domain/0afbc3c0-5638-4248-bd9a-9f3c7ab0f6cd, for example. This PR makes a few improvements:
- Reduce worker concurrency from 100 -> 20. This might address #156 (as I tested running 20 workers at a time before with no problem), and the entire scan should still take around an hour.
- Make logging from worker more descriptive, so it's easier to search log groups to tell which files actually contained relevant domains (by searching for "got some results")
=> Censys IPv4 enhancements

backend/src/api/users.ts, backend/test/users.test.ts
This PR updates a user's name on invite, if their account already exists. This is helpful when users are invited after an account is created, as their name is initially blank.
=> Update user name on invite

backend/src/models/scan-task.ts
I don't think `onUpdate: 'SET NULL'` makes any sense.
=> Set onUpdate: 'CASCADE' for scan -> scantasks relationship

backend/src/tasks/censysIpv4.ts
Somehow, using `got` with the earlier auth parameters for the censys api endpoint / details url requests doesn't work and returns a 403 unauthorized request. I've changed these requests to use axios instead.
I deployed the workers and tested, and the axios version worked.
This issue doesn't appear to happen for the .gz files, so I continue to use `got` for that request.
Related to https://github.com/sindresorhus/got/issues/1169
=> censys ipv4 - use axios for getting data instead of got

backend/src/tasks/censysIpv4.ts, frontend/src/components/ServicesTable/ServicesTable.tsx
- Show full censys results in the services description. Fixes #188
- Let censys ipv4 scan dummy data work again on localhost. I think the change you made to the code @cablej essentially made it so that it would get nearly zero results.
=> Censys ipv4 fixes

backend/jest.config.js, backend/src/tasks/censysIpv4.ts, backend/src/tasks/helpers/__mocks__/saveServicesToDb.ts, backend/src/tasks/test/__snapshots__/censysIpv4.test.ts.snap, backend/src/tasks/test/censysIpv4.test.ts
Sanitize (remove null characters) from the `censysIpv4Results` field as well. This fixes a db error in which we would still get something like this:
```
db_1         | 2020-08-02 15:18:14.714 UTC [716] ERROR:  unsupported Unicode escape sequence
db_1         | 2020-08-02 15:18:14.714 UTC [716] DETAIL:  \u0000 cannot be converted to text.
db_1         | 2020-08-02 15:18:14.714 UTC [716] CONTEXT:  JSON data, line 1: ...":{"is_ca":true},"certificate_policies":[{"cps":[...
db_1         | 2020-08-02 15:18:14.714 UTC [716] STATEMENT:  INSERT INTO "service"("id", "port", "service", "lastSeen", "banner", "censysMetadata", "censysIpv4Results", "domainId") VALUES (DEFAULT, $1, $2, $3, $4, DEFAULT, $5, $6) ON CONFLICT 
db_1         |          ("domainId","port") DO UPDATE
db_1         |          SET …
```
=> Sanitize CensysIpv4 scan results

frontend/src/components/Header/Header.tsx
This way, we won't confuse this with the actual `global` property of the scan schema.
=> Rename "Global Scans" -> "All Scans" in navbar

backend/package.json, docs/contributing/setup.md
Add npm shortcuts for running syncdb and scheduler. Taking this change out of #196.
=> Add npm shortcuts for running syncdb and scheduler

backend/src/tasks/scheduler.ts, backend/src/tasks/test/scheduler.test.ts
Fixes scheduling logic so that if _any_ task is already running, the scheduler will not schedule a new task. This fixes the issue in which too many tasks were launched by CensysIpv4, because as soon as one chunk (out of 20) had finished, the scheduler would end up launching more tasks (when it really needs to wait until all 20 tasks have finished).
Fixes #195.
=> Fix scheduling logic for CensysIpv4

.github/workflows/backend.yml, backend/jest.config.js, docs/contributing/setup.md
Collect code coverage on the backend -- this way we can enforce that any additional changes will have some level of tests added to them. I've added a conservative threshold, 50% branch coverage (right now we're a few points above that).
It also generates nice HTML reports that look like this:
=> Add a code coverage CI check for backend

backend/src/api/domains.ts, backend/src/api/vulnerabilities.ts, backend/test/domains.test.ts, backend/test/vulnerabilities.test.ts
Fixes #238 so that when passing in `organization` as a filter, it properly filters domains / vulnerabilities shown.
=> Add an organization filter to domains / vulnerabilities

.github/workflows/frontend.yml, infrastructure/frontend.tf
This is in relation to #158.
Following the guidence for create-react-app [here](https://create-react-app.dev/docs/production-build/), this will:
- Cache all assets under build/static for a month, they are named using hashes during the CRA build process and will be unique for each build
- Don't cache anything else, includes `index.html`, `robots.txt`, etc
- Most recent `index.html` will always be fetched, which will contain references to most recent static assets from the build. 
@epicfaace I think this is what you meant. I don't think a cloudfront invalidation is necessary since it should respect the `cache-control` header from s3.
More seamless frontend deploys
Verify Caching behavior in s3/cloudfront on deploy to staging.
=> Prevent non-static assets from being cached by cloudfront

backend/src/tasks/scheduler.ts, backend/src/tasks/test/scheduler.test.ts
Fixes #242 by setting the lastRun column only if it was run.
=> Scans -- set the lastRun column only if it was run

frontend/src/pages/Domain/Domain.tsx
Fixes #265. Now, the page will just be blank next to "organization":
=> Fix domain page for undefined orgs

backend/src/tasks/scheduler.ts, backend/src/tasks/test/scheduler.test.ts
Currently, the scheduler will continuously retry a failed scan, as it checks to see when a scan last succeeded in order to determine if it should be run. This PR changes this logic so that a scan will not be continuously retried when it fails, which prevents possibly high resource consumption and traffic generation from repeatedly failing scans.
=> Don't retry scan if recently failed

backend/src/tasks/cve.ts
From documentation:
```
-require_version
ignore matches of CPEs with version ANY
```
This will reduce the number of false positive vulnerabilities detected by Crossfeed.
=> Add require_version scan to cpe2cve

backend/src/tasks/amass.ts, backend/src/tasks/findomain.ts, backend/src/tasks/portscanner.ts, backend/src/tasks/test/wappalyzer.test.ts, backend/src/tasks/wappalyzer.ts
This PR fixes several bugs with scans:
- Several scans, including portscanner, findomain, and amass, would fail if any individual component threw an error (e.g. a single IP for portscanner or single host for findomain). This adds error handling to prevent failing in that case.
- Wappalyzer would create a new domain without any organization, which would lead to results not displaying. This changes the logic to directly save the updated domain. We might want to consider adding a `{nullable: false}` constraint to the domain model to prevent having domains without an organization, though this would be a breaking change that would require deleting the domain table without having migrations (maybe a good time to make a bastion DB lambda function?)
=> Scan bug fixes

.github/workflows/backend.yml
Port 80 takes the longest to get ready because it serves the React code. We don't really need to do this, and this will make our tests a bit less flaky.
=> Don't wait for port 80

backend/serverless.yml
This permission is needed to be able to access logs.
=> Add logs:GetLogEvents permission to serverless

docker-compose.yml
It looks like there's a known bug I've been running into with React in docker where it will periodically crash without this setting.
https://dev.to/igmrrf/docker-react-exited-with-code-0-398n
=> Add tty: true to docker-compose

package.json
For convenience, this lets you just run `npm start` from the root directory instead of having to type in `docker-compose up --build`.
=> Easier start script

backend/src/api/auth.ts, backend/src/api/users.ts
This prevents invites from not working if the case of emails doesn't match by converting all email addresses to lower case first.
=> Convert emails to lowercase

infrastructure/prod.config, infrastructure/stage.config
AWS_PROFILE is not a valid configuration for the s3 backend, but [profile](https://www.terraform.io/docs/backends/types/s3.html#profile) is.
=> Fix terraform CI builds by changing AWS_PROFILE -> profile

infrastructure/database.tf
I don't see any reason why we would want to make it smaller. We may also want to eventually look into preserving all our backups, even beyond 35 days.
=> Increase RDS retention period to max (35 days)

backend/src/tasks/censysIpv4.ts, backend/src/tasks/helpers/__mocks__/getAllDomains.ts, backend/src/tasks/helpers/getAllDomains.ts, backend/src/tasks/test/__snapshots__/censysIpv4.test.ts.snap
This fixes a bug with the CensysIPv4 scan where organizations wouldn't be included when updating a domain.
=> Include organization in censysipv4

frontend/package.json, frontend/public/index.html
Fixes #343 (this issue is on the old Edge, not the new Edge with Chromium).
Apparently, just turning off quirks mode with the `<!DOCTYPE html>` fixed it  ¯\_(ツ)_/¯
I also changed the browserslist attribute so that I could test the site on Edge in development mode.
=> Fix Microsoft Edge ToS issue

backend/jest.config.js, backend/src/tasks/ecs-client.ts, backend/src/tasks/test/__snapshots__/ecs-client.test.ts.snap, backend/src/tasks/test/ecs-client.test.ts
Fixes #374 by passing in the right logStreamName parameter to the AWS CloudWatch API.
=> Fix log fetching from CloudWatch

backend/src/api/auth.ts, backend/test/auth.test.ts
- If a user switches auth providers (from cognito to login.gov, for example), the new auth provider's id will be stored on the User object, as well as the old. Previously, we were storing the auth provider's id only on creation.
- Additionally, if a user changes ids within an auth provider (for example, if their cognito user gets deleted and recreated), the new auth provider's id will be updated on the user model.
=> Better define behavior when switching between auth providers

backend/env.yml
Addresses failing deploys, noted in #389. We don't need either of these env variables, because the worker grabs these variables directly from SSM (see the terraform definition).
I'd imagine that WORKER_SIGNATURE_PRIVATE_KEY is the largest env variable we have.
=> Remove WORKER_USER_AGENT and WORKER_SIGNATURE_PRIVATE_KEY from env variables

backend/env.yml
This variable actually doesn't come from SSM, so it's needed for our user agent string to be sent from the worker. We could later retrieve it from SSM, though.
=> Re-add WORKER_USER_AGENT

frontend/src/pages/Scans/ScanTasksView.tsx
As per what we discussed in the UX meeting -- saying that a scantask's end time is "Never" could give the impression that the scantask will never end.
=> Change "Never" to "None" for less confusion on date formatting

backend/env.yml
Sets the REACT_APP_USER_POOL_ID for the backend to fix the prod deploy. I've gone ahead and deployed this to prod already, so it's working.
Fixes #401.
=> Fix prod deploy

backend/src/models/service.ts, backend/src/models/test/__snapshots__/service.test.ts.snap, backend/src/models/test/service.test.ts
- Ignore Tomcat 1.1 version in the `products` array. This is a false positive reported by wappalyzer (https://github.com/AliasIO/wappalyzer/issues/3305).
- Fixed an issue where if censysMetadata is an empty object, an empty product with this value would be added to `products`:
```
Object {
"cpe": undefined,
"description": undefined,
"name": undefined,
"product": undefined,
"revision": undefined,
"tags": Array [],
"version": undefined,
}
```
=> Ignore wrong Tomcat version, add filtering / tests for setProducts

.github/workflows/docs.yml
I already added the CNAME manually by going into Settings and setting the custom domain, but this PR ensures that this file is added on every GitHub Pages build.
Also, fix a typo with JEKYLL_ENV.
Finally, removes the baseurl option so that the docs site can be published at https://docs.crossfeed.cyber.dhs.gov/.
=> Fix GitHub Pages deployment to custom domain

infrastructure/users.tf
I don't think this parameter has any effect, especially given that `localhost` isn't used on prod.
=> Remove callback_urls from cognito user pool

infrastructure/users.tf
Reverts cisagov/crossfeed#431
We apparently need this, or we get the error
```
Error updating Cognito User Pool Client: InvalidOAuthFlowException: CallbackUrls can not be empty when code flow or implicit flow is selected
```
https://github.com/cisagov/crossfeed/runs/1103766857
=> Revert "Remove callback_urls from cognito user pool"

backend/serverless.yml
Add API Gateway logs so we can log which endpoints on the API are called. Requests are logged to CloudWatch.
=> Add API Gateway logs

backend/src/models/domain.ts, backend/src/models/organization.ts, backend/src/models/scan.ts, backend/src/models/service.ts
Currently, when a scan is deleted, this will cause any discovered domains to be deleted due to an associated ManyToOne cascade relationship. This PR fixes this so that rows aren't deleted when certain associated rows are deleted.
=> Don't delete rows when certain associated rows are deleted

backend/src/models/service.ts
Excludes F5 from Intrigue Ident, which leads to some false positives. We should eventually move this into the application process so we don't need to commit each time we flag a false positive.
=> Exclude F5 from Intrigue Ident, fix cpe format

backend/src/api/app.ts, backend/test/scan-tasks.test.ts
Rather than using res.send on errors, which can be vulnerable to XSS attacks if user data is included, this changes handlerToExpress to use res.json on a parsing error.
=> Use res.json on error

.github/dependabot.yml
As a followup to #547 -- we need to ignore typescript so that this change doesn't get automerged again.
=> Ignore typescript for frontend dependabot updates

docs/contributing/deployment.md, infrastructure/es.tf
This will fix the prod deployment issues. Essentially, we need one elasticsearch service-linked role for AWS elasticsearch to function from within a VPC, but we can't have more than one. From https://github.com/terraform-providers/terraform-provider-aws/issues/5218, it appears that the best way to do this is just to perform a one-time creation of the role outside Terraform.
=> Move elasticsearch service-linked role out of Terraform

backend/src/api/scan-tasks.ts, backend/src/tasks/scheduler.ts, backend/src/tasks/test/scheduler.test.ts
- When a failed scan occurred without a finishedAt column, this would cause the scheduler to immediately schedule a new scan, when. Changes the scheduler logic to ignore such scantasks to prevent this bug.
- Make sure that finishedAt is always set whenever a scan is 1) manually killed or 2) fails due to an ECS error with RunTask (these were the two cases in which the bug above would occur).
=> Scheduler - handle failed tasks without a finishedAt column

frontend/package-lock.json, frontend/package.json
Our tests broke when we upgraded the `@testing-library/react` package.
See release notes in https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0 for more information
=> Fix frontend tests by using jsdom 16

backend/src/tasks/search-sync.ts, backend/src/tasks/test/search-sync.test.ts
Fixes the OOM errors we've been seeing with search-sync on production.
- search-sync only syncs a maximum of 500 domains at a time
- search-sync gets only the domainIds that need syncing, rather than having to loop through all domains each time
- Add more exhaustive tests
=> More efficient search-sync for domains

backend/src/api/stats.ts
Turns out, `take` doesn't have an effect on any of these queries, so I removed the usage of `take` where we don't want to limit anything. Changed the "numVulnerabilities" graph to have a limit of 50 so that we can actually read the domain names on the x-axis of that graph.
=> Limit results to 50 in "numVulnerabilities" graph

backend/src/tasks/censysIpv4.ts
Fixes #622 -- this issue was likely caused because when censys is called in a non-granular fashion, an empty array is passed to `organizations` instead of `undefined`. This ends up adding `()` in the query builder, causing a syntax error.
=> Fix censys scan issue by never passing an empty array of organizations

backend/src/api/scans.ts, backend/src/tasks/censysIpv4.ts
Trying to fix #624. It appears that censys usually runs well, except for that it fails at the end, so maybe we're just running out of memory?
=> Reduce censys concurrency, add CPU / memory

infrastructure/main.tf, infrastructure/worker.tf
For consistency with all other SSM variables. Also, we would end up accidentally constantly changing the tag for "stage_api_domain" from staging -> prod -> staging etc. because of how the tags were set up.
=> Terraform - Remove "stage" tags from ssm parameters, for consistency

frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
Link vulnerability names to the NVD site, so the user doesn't have to expand each vulnerability to get the URL for the CVE.
Screenshot (test data):
=> Link vulnerability names to NVD

backend/src/tasks/s3-client.ts, backend/src/tasks/search-sync.ts, backend/src/tasks/test/s3-client.test.ts, infrastructure/worker.tf
Fixes #643. This was due to two problems:
- When the S3 file doesn't exist in the bucket, it currently just crashes. This PR makes it just return an empty body in those cases.
- The worker doesn't have the "ListObjects" permission for the bucket, so a 404 will show up as a 403 error. This PR adds in that permission, so a 404 error is properly shown.
Also, changes searchSync to only sync 100 webpages at a time, because it appears that the batch size of 500 is still too large for a single t2.micro ES instance to handle at all.
=> searchSync - better error handling when s3 files don't exist

frontend/src/pages/Search/SearchProvider/buildRequest.js
explicitly match_all when search term is empty in buildChildMatch for webpage search
Was getting this error when search term is empty string (initial page load / all results). @epicfaace let me know if I missed something. This is the backend error I was getting causing a 500.
Visit search page with empty filter
=> fix: broken search for webpage_body when search term is empty

infrastructure/es.tf, infrastructure/prod.tfvars, infrastructure/stage.tfvars, infrastructure/vars.tf
Scale down elasticsearch on staging and scale up elasticsearch on prod. Fixes #571
Previously, we were paying for 2 t2.small.elasticsearch clusters -- this is 25.92 * 2 = $51.84 / month.
Now, we'll be paying for 1 t2.micro.elasticsearch and 3 t3.small.elasticsearch clusters -- this is 12.96 + 25.92 * 3 = $90.72 / month.
=> Scale up elasticsearch on prod

infrastructure/stage.tfvars
Didn't realize that "The t2.micro.elasticsearch instance type supports only Elasticsearch 1.5 and 2.3."
=> Use t2.small.elasticsearch for staging

backend/src/tasks/search-sync.ts, backend/src/tasks/test/es-client.test.ts, backend/src/tasks/test/search-sync.test.ts
Each searchSync scan now performs the syncing in chunks, and repeatedly does so until all domains / webpages have been synced.
This will fix the current issues we're having with our elasticsearch domains running out of memory on prod with the searchSync scans.
=> Perform searchSync in chunks

backend/src/tasks/search-sync.ts
searchSync is still failing on prod with the error `'403 Request throttled due to too many requests /_bulk'` - hopefully these changes should fix it.
=> searchSync - reduce chunk size for domains, add retries

frontend/src/components/DomainDetails.tsx
Adds a sitemap display to a domain, which displays the sitemap as a nested tree with collapsable sections:
Fixes #664.
=> Add sitemap display

backend/src/models/domain.ts, backend/src/models/service.ts, backend/src/models/webpage.ts
Deleting a scan can time out as the current onDelete actions take a while. This removes those to improve performance.
=> Remove ondelete for discoveredBy

backend/src/tasks/scheduler.ts, backend/src/tasks/test/scheduler.test.ts
This is a fix to the bug in the scheduler that was changing the lastRun variable in scans that had not been run yet.
For each scan that is checked in the run() function, a variable tracks the previous number of launched tasks. Then in the final if statement in run(), it checks to see if there is difference between the previous number of launched tasks and the current number. If there is, then that scan specifically has been run and it's lastRun variable can be updated, along with manualRunPending.
See issue #713 
All previous tests pass. Through dev tools and console logs, I verified that the bug no longer occurs.
Test added to scheduler.test that sets the proper conditions for the bug and ensures it's fixed.
=> Scheduler bugfix

infrastructure/es.tf
Add INDEX_SLOW_LOGS, SEARCH_SLOW_LOGS, AUDIT_LOGS
Elasticsearch has been sometimes slow with queries in prod (sometimes up to 10 seconds or more), so this should help us analyze what's causing the slowness.
=> Add additional elasticsearch logs

infrastructure/es.tf
Temporarily revert until we can fix the error, "ValidationException: audit log publishing cannot be enabled as you do not have advanced security options configured."
=> Disable ES audit logs

frontend/src/pages/AuthLogin/AuthLogin.tsx
Looks like Amplify uses the same label for the 2FA prompt screen and the "Reset Password" screen...
=> Revert code textbox change

backend/env.yml
This is causing all endpoints on prod to fail with:
```
Mon Oct 19 02:54:49 UTC 2020 : Lambda execution failed with status 200 due to customer function error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}. Lambda request id: 474e74e7-7222-4364-b0f5-886d71814ad6
```
=> Fix MATOMO_URL for prod

backend/src/tasks/es-client.ts, backend/src/tasks/helpers/saveWebpagesToDb.ts, infrastructure/es.tf
Helps with the bulk rejections that we are seeing on dev / prod.
- update refresh_interval to 60s to make indexing less memory-intensive (default is 1s)
- increase ES volume size
- use randomized retries when syncing webpages to elasticsearch
Fixes #744.
=> Make elasticsearch indexing more resilient

backend/src/tasks/es-client.ts, backend/src/tasks/helpers/saveWebpagesToDb.ts, backend/src/tasks/webscraper.ts
Still having some issues with bulk requests getting throttled, especially when we have concurrent instances of webscraper running. This PR:
- Sets refresh_interval to 300s
- Indexes webpages in batches of 10, not 100
- Increases # of retries for webpage indexing
- prints less output (so logs are smaller, more concise)
- fixes a bug where scraper would crash when `insertedWebpage` is undefined (not sure when / why this is happening though)
=> Make elasticsearch even more reliable

infrastructure/es.tf
We ran out of space -- getting this error now in searchSync:
```
2020-10-20T12:06:49.924Z {
2020-10-20T12:06:49.924Z   type: 'cluster_block_exception',
2020-10-20T12:06:49.924Z   reason: 'index [domains-5] blocked by: [FORBIDDEN/8/index write (api)];'
2020-10-20T12:06:49.924Z } {
```
=> Increase elasticsearch disk size

frontend/src/components/DomainDetails.tsx, frontend/src/components/__tests__/__snapshots__/domainDetails.spec.tsx.snap, frontend/src/components/__tests__/domainDetails.spec.tsx
Fixes #729 by fixing the logic in `generateWebpageList`. Also added tests for `generateWebpageTree`.
=> Fix URL display with trailing slashes

backend/src/api/app.ts
This code actually has no effect, as calling `delete` on the token will not prevent the original `Cookie` header from being sent over to other middleware.
This code (which is already there) already prevents `crossfeed-token` from being sent to Matomo:
https://github.com/cisagov/crossfeed/blob/a8f86bc0b18fc0a62a0dcae53e11fd640a100626/backend/src/api/app.ts#L124-L132
=> Remove unneeded code for crossfeed-token

infrastructure/es.tf
We ran out of space again, so webscraper is failing...
=> Upgrade elasticsearch storage again

backend/src/api/domains.ts
Many of the domain pages aren't loading at all (they're timing out), so let's disable showing webpages on the domain page for now so those pages can work at least.
=> Don't show webpages on domain page for now

.github/workflows/backend.yml, backend/package.json, backend/src/tasks/es-client.ts, backend/src/tools/run-syncdb.ts
- Use term vector for webpage_body, fixes #782
- Run syncdb faster (without using docker-compose -- using ts-node instead)
=> Use term vector for webpage_body

frontend/src/components/ColumnFilter/ColumnFilter.tsx
Fixes bug where pushing enter twice on a table filter results in clearing the filter.
Adds type to clear button 
Issue #801
=> Fixes clear on searching twice

infrastructure/database.tf
Otherwise, CI gets an error, "Cannot upgrade postgres from 11.8 to 11.5". See https://github.com/cisagov/crossfeed/pull/818/checks?check_run_id=1333557652
Not sure how this was automatically upgraded, though...
=> Upgrade postgres

backend/src/tasks/cve.ts, backend/src/tasks/test/cve.test.ts
2 days is too short and sometimes causes us to accidentally close vulnerabilities that should actually be open.
=> CVEs - Change two-day threshold to one week

backend/src/api/login-gov.ts
Scans were failing due to the `LOGIN_GOV_JWT_KEY` variable not being set. This allows the app not to crash when that is not set.
=> Fix failing scans

frontend/src/context/AuthContextProvider.tsx
Fix infinite refresh on login screen by refreshing the page only when a token was defined previously.
=> Fix infinite refresh on login screen

backend/worker/requirements.txt
cryptography should be pinned to 2.9, as our version of mitmproxy doesn't work with versions > 3.0.
=> Fix CI build by reverting dependabot bump

docs/Dockerfile
Fixes #892 by pinning the node version in the docs Dockerfile.
Also fix the order of build statements; otherwise the generated API swagger file was being overwritten and thus not allowing the docs site to build.
=> Pin node version in docs dockerfile to fix build errors

infrastructure/worker.tf
Make webscraper bucket deletable by setting force_destroy equal to True. Once we deploy to prod once, then we can delete the bucket from Terraform and it should properly delete both the bucket and all its contents.
=> Make webscraper bucket deletable

backend/src/tasks/test/__snapshots__/webscraper.test.ts.snap, backend/src/tasks/test/webscraper.test.ts
Fix flaky webscraper tests by sorting webscraper results. This test has been intermittently failing in recent CI runs.
=> Fix flaky webscraper tests by sorting results

backend/src/api/domains.ts, backend/test/domains.test.ts, backend/test/vulnerabilities.test.ts
Add tag support for domain search / export endpoints. This way, we can specify `tag: "[tagId]"` when calling these endpoints.
We already have tag support for the vulnerability search / export endpoints. This PR also adds tests for the existing vulnerability functionality.
=> Add tag support for domain search / export

backend/src/api/domains.ts, backend/src/api/scan-tasks.ts, backend/src/api/vulnerabilities.ts, backend/test/vulnerabilities.test.ts
- Fix count queries for vulnerabilities by not hardcoding the count to 10000. This would cause issues where the vulnerabilities page would always show "10000 results", even if there were less:
- Improve count queries for scantasks / domains by using the `getManyAndCount()` function, instead of duplicating the same query task using both `getMany()` and `getCount()`
=> Fix count queries for domains / scantasks / vulnerabilities

backend/src/tasks/scheduler.ts
- Log the number of organizations a particular launched ScanTask is associated with
- Log when a scan / scan + organization combination is skipped
This will make it easier to debug issues such as #939.
=> Add more logging to scheduler

.github/workflows/backend.yml
This reverts commit e91e0c1841da3b804198517c4b3729ffb7aa4c56.
As the axios version bump (#899) has now been merged, we can now re-add the security checks to the backend GHA pipeline. Fixes #936.
=> Revert "disable security pipeline check for now"

backend/src/api/auth.ts
Increase jwt expiration time to 3 days, as 1 day makes it really inconvenient to have to login / enter 2FA codes every single day. We should later implement a "Keep me signed in" and/or refresh token mechanism so this option can be more flexible and configurable.
=> Increase jwt expiration time to 3 days

frontend/src/pages/Scans/MultiSelect.tsx
Fixes #847, making it easier to associate a scan with a large number of organizations.
The MultiSelect now overflows properly:
=> Fix MultiSelect overflow height

frontend/src/pages/Organization/Organization.tsx
Fixes #935. Now, clicking on the "Cancel" button from an Organization detail page will properly go back to the organization list page (`/organizations`).
=> Fix Cancel button for Organization page

backend/src/worker.ts
Fix an issue with global scans not running that was introduced by #920. Because the new logic introduced would loop through all selected organizations to run the worker scan code, this would end up not running the scan code at all for global scans (which have the `.organizations` property set to an empty array).
=> Fix issue with global scans not running

backend/src/models/service.ts, backend/src/tasks/shodan.ts, backend/src/tasks/test/__snapshots__/shodan.test.ts.snap, backend/src/tasks/test/shodan.test.ts
Fixes #951, in which results from shodan would cause multiple CPEs to be saved incorrectly. Now, we just ignore the `product` and `version` keys altogether and just create a new product for each CPE in the `cpes` array.
Also, stop creating vulns from shodan now -- there are too many false positives, and we can't easily determine which CPE caused the particular vuln indicated by shodan.
=> Fix bug where shodan mismatches CPEs

backend/src/api/domains.ts, backend/test/domains.test.ts
Add organizationName to domains export -- this makes the domains export more useful as we can see which domains belong to which organizations.
=> Add organizationName to domains export

backend/src/tasks/cve.ts, backend/src/tasks/test/__snapshots__/cve.test.ts.snap, backend/src/tasks/test/cve.test.ts
Fix cve scan on CPEs that already contain version numbers; fixes #961. This way, the CPEs will be properly input into the `cpe2cve` command-line tool.
=> Fix cve scan on CPEs that already contain version numbers

backend/src/api/scans.ts, backend/src/tasks/cve.ts, backend/src/tasks/ecs-client.ts, backend/src/tasks/search-sync.ts, backend/src/tasks/wappalyzer.ts
Attempts to address #961 by better batching domains in the cve scans, so that less memory is used. Also increases the memory used for the cve scans in general to 8192 (8 GB).
Finally, adds a 4 GB memory limit for local scans being run through Docker, to better emulate the Fargate memory constraints.
=> Better batch domains in cve scan to meet memory limits

.github/workflows/backend.yml, backend/src/tasks/test/wappalyzer.test.ts
Make backend tests log less. The `--silent` option in jest suppresses all `console.log` output. Otherwise, tests log a lot of output and it's cumbersome to scroll through all the output (see https://github.com/cisagov/crossfeed/runs/2026577665 for an example).
=> Make backend tests log less

frontend/package-lock.json, frontend/package.json
node-sass doesn't work on mac if you want to run the frontend outside of Docker. Additionally, sass is faster / has less installation problems than node-sass.
=> Replace node-sass with sass

backend/src/api/scans.ts
The wappalyzer scan is often failing on prod with the message, "Killed." This PR increases the cpu and memory for that scan so that hopefully it will fail less often.
=> Increase cpu and memory for wappalyzer scan

frontend/src/context/userStateUtils.ts
Expand CISA internal users that don't need to sign TOS to users with email address `@associates.cisa.dhs.gov`.
=> Expand CISA internal users that don't need to sign TOS

infrastructure/database.tf
Scale prod db disk storage to 100 GB to fix out-of-disk-space errors with large domain exports.
=> Scale prod db disk storage to 100 GB

backend/src/tasks/test-proxy.ts, docs/src/documentation-pages/contributing/setup.md, package.json
Build docker containers faster, in parallel, when running locally. Previously, they would just build serially.
Also updated the setup documentation a bit.
=> Build docker containers faster, in parallel

backend/src/api/domains.ts, backend/test/domains.test.ts
Fix domains export to include product names and ports. Previously, these columns would just be empty or show `[object Object]`.
=> Fix domains export to include product names and ports

backend/src/models/service.ts
Fixes #1015. Fixes a product name showing up as "undefined"; instead, the product CPE is shown, and if that is also undefined, just shows the text "Unknown."
Screenshot:
=> Fix "undefined" product name, fixes #1015

frontend/src/components/Table/Table.tsx
Fix domain pagination issues where number of pages is overestimated, by ensuring that the right `pageSize` is sent to the backend. Previously, a `pageSize` of 25 was sent to the backend but the frontend estimated page numbers based on a `pageSize` of 15. With this change, a `pageSize` of 15 will be used throughout.
Fixes #1011.
=> Fix domain pagination issues where number of pages is overestimated

backend/src/api/search.ts, frontend/src/context/SearchProvider/SearchProvider.tsx
Fixes #949.
Gives an organization-specific key to the `ESProvider` component so that the search results page properly resets when the current organization is changed.
=> Fix Inventory page refresh when org dropdown changes

infrastructure/worker.tf
Delete webscraper bucket -- we're not using this anymore. This failed to delete earlier due to GHA issues with running Terraform commands, but hopefully it should succeed this time after those Terraform issues were fixed.
=> Delete webscraper bucket

docs/gatsby-config.js, docs/gatsby-node.js, docs/src/components/highlights.js, docs/src/components/nav.js, docs/src/components/sidenav.js, docs/src/documentation-pages/usage/product-overview.md, docs/src/templates/documentation-page.js
- Generate correct slugs based on file path (so `/contributing/deployment/` instead of just `/deployment/`)
- Highlight top nav item when on a subpage:
=> Documentation: Generate correct slugs, highlighting

.github/workflows/infrastructure.yml
Increase terraform CI timeout to the maximum level of 72 hours. This is because it's taking over 6 hours to delete the S3 webscraper buckets.
=> Increase terraform CI timeout to 72 hours

backend/src/tasks/cve.ts, backend/src/tasks/test/__snapshots__/cve.test.ts.snap, backend/src/tasks/test/cve.test.ts
For #961 -- include alternate IIS CPEs. We would receive `cpe:/a:microsoft:internet_information_server` from our data sources, but putting that into NVD gives us no results because the CPE has been renamed to `cpe:/a:microsoft:internet_information_services` instead (which _does_ give us several vulnerabilities as results).
=> Include alternate IIS CPEs

backend/src/api/scans.ts, backend/test/scans.test.ts
Fixes #680 
Edited the granular scans api to exclude scans that only run once.
Updated tests to reflect this change
Change was required because the API was returning irrelevant scans.
The tests now check to make sure that no single scans are returned by the API
=> Fix Granular scans to exclude single scans and update tests 

backend/src/tasks/cve.ts, backend/src/tasks/test/__snapshots__/cve.test.ts.snap, backend/src/tasks/test/cve.test.ts
Fix IIS vulnerability renaming logic, as the old logic wasn't properly working for cpes with version numbers and the cpe `cpe:/a:microsoft:iis`.
For https://github.com/cisagov/crossfeed/issues/961
=> Fix IIS vulnerability renaming logic

backend/src/api/scans.ts
The shodan scan is getting killed due to a lack of memory. This PR increases cpu, memory for the shodan scan to make it more robust.
=> Increase cpu, memory for shodan scan

backend/src/tasks/helpers/saveVulnerabilitiesToDb.ts, backend/src/tasks/shodan.ts, backend/src/tasks/test/shodan.test.ts
Save vulnerability data from shodan. I had disabled this earlier because it was a bit unreliable, but I think with a few changes, we're ready to enable it again. This will allow us to bring in vulnerability data from shodan (such as data from the latest Exchange vulnerabilities).
I also add additional logic to `saveVulnerabilitiesToDb` so that vulnerability data from shodan doesn't inadvertently overwrite vulnerability data from other sources, such as the cpe2cve tool.
=> Save vulnerability data from shodan

frontend/src/pages/Users/Users.tsx, frontend/src/test-utils/user.ts, frontend/src/types/user.ts
Fixes https://github.com/cisagov/crossfeed/issues/1049. `lastLoggedIn` is an ISO String, not a date, so this PR changes the typing accordingly.
It looks like `dateAcceptedTerms` was also earlier incorrectly typed as a date rather than a string, so I've changed that as well and formatted this date in the user table with `formatDistanceToNow` as well.
=> Fix last logged in bug for user table

backend/package.json, docs/src/documentation-pages/dev/database.md, docs/src/documentation-pages/dev/quickstart.md
Simplify syncdb command so the user can just run `npm run syncdb` again (instead of copy-and-pasting a long `docker compose` command).
=> Simplify syncdb command

frontend/src/components/Header.tsx, frontend/src/components/__tests__/__snapshots__/header.spec.tsx.snap, frontend/src/context/Theme.tsx
fixes #979 
All 4 NavItems only fit side by side when the screen width is 1330px or greater.
The original code tried to fix this by hiding  the "scan" nav item when the screen width was <1280px ('lg'). Instead of hiding one of the navItems, I made the sidebar button accessible until all four can be shown side-by-side. 
See changes at width: 1330px below:
=> Navbar "scans" tab disappears when screen size is too small #979

backend/src/tools/run-syncdb.ts
Sorry, I didn't test https://github.com/cisagov/crossfeed/pull/1036 properly -- we need to fix the endpoints for syncdb because it's now being run from within the backend docker container (so the endpoints for the database and elasticsearch should be `db` and `es`, respectively, not `localhost`).
=> Fix endpoints for syncdb

frontend/src/components/SearchBar.tsx
fixes #1083
Changed the search icon and preview text colors:
Original:
Fix:
=> A5 - Text and Search Icon Color

backend/src/tasks/hibp.ts, backend/src/tasks/sample_data/vulnerabilities.json, backend/src/tasks/test/hibp.test.ts
Fixes #1075
In order to Generate P&E reports the HIBP data needs to have data about each breach. This update adds the breach data to structured data field in the vulnerability model alongside the exposed emails
=> Add Breach Data to HIBP Scan

.github/workflows/docs.yml
We were getting some warnings / errors on the GH Pages workflow -- it should actually be target_branch: https://github.com/crazy-max/ghaction-github-pages
=> Fix typo -> target-branch to target_branch

backend/Dockerfile.worker
Makes the worker dockerfile smaller. See https://stackoverflow.com/questions/45594707/what-is-pips-no-cache-dir-good-for
=> Optimize pip install with --no-cache-dir

.github/workflows/backend.yml, .github/workflows/frontend.yml, .github/workflows/infrastructure.yml, docs/src/documentation-pages/dev/deployment.md
In this PR, [environments](https://docs.github.com/en/actions/reference/environments) are configured to ensure that only specific users with the appropriate permissions can trigger workflows on GitHub Actions or access secrets that perform deployments. At the moment, GitHub Actions jobs that deploy to staging and prod or access credentials for those AWS environments must be [manually approved](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) by me. Fixes https://github.com/cisagov/crossfeed/issues/1155.
The AWS access secrets are only accessible for workflows that specify an environment (`staging` or `prod`), and these workflows have also been set to have a concurrency of 1 (so we don't have multiple deployments at the same time). I've also renamed the …
=> Use environments to secure deployments

docs/src/components/sidenav.js
Added a link to https://docs.crossfeed.cyber.dhs.gov/dev/own-instance/ to the docs menu sidebar, which was mistakenly not added earlier.
=> Add link to setting up your own instance

frontend/src/pages/Search/ResultCard.tsx
Fixes #1090
Changed padding from 1.5 rem to .875 rem to make it 14px for the padding.
=> Reduce Padding on Search Results Page to Reflect Design

infrastructure/worker.tf
Adds a lifecycle rule to the export bucket to automatically delete objects after 1 day.
Eliminates unnecessary storage/security risks as exported files don't need to be saved after they are downloaded.
=> Add export bucket expiration

frontend/src/pages/Search/Dashboard.tsx
Fixes #1093
Adjusted the shadow on the Footer to match the design prototype.
=> Adjusted Shadow on Footer to match design

dev.env.example
I've been seeing this issue (https://support.snyk.io/hc/en-us/articles/360002046418-JavaScript-heap-out-of-memory) often, adding a fix to increase the amount of memory allocated to Node.
=> Fix "heap out of memory" issues for frontend

backend/src/api/scans.ts, backend/src/tasks/dotgov.ts, backend/src/tasks/test/__snapshots__/dotgov.test.ts.snap, backend/src/tasks/test/dotgov.test.ts, backend/src/worker.ts, frontend/src/pages/Scans/ScanTasksView.tsx
Add scan to import dotgov domains (from https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv).
The scan creates organizations based on root domains from the dotgov registrar dataset. All organizations are created with the "dotgov" tag and have a " (dotgov)" suffix added to their name.
=> Add scan to import dotgov domains

.github/workflows/backend.yml, backend/webpack.backend.config.js, backend/webpack.worker.config.js
This will prevent more errors when deploying and ensure we catch them at the PR stage.
=> Add package step to CI, fix CI

frontend/src/styles.scss
Found the solution here:
https://github.com/aws-amplify/amplify-js/discussions/7820
fixes #1309 
Login screen now looks like it did before
:
=> Fixed Login Styling Issue

backend/src/api/scans.ts, backend/src/tasks/test-proxy.ts, backend/src/worker.ts
Fix and clarify test-proxy scan instructions. This scan is used to test the proxy (which adds in the user-agent and signs all requests from Crossfeed) and is only run locally on the command line.
Clarify how to set up and check the webhook URL, and also fix some bugs that were making the test-proxy scan fail earlier.
=> Fix and clarify test-proxy scan instructions

infrastructure/kms.tf
Fix terraform deployment by adding proper kms permissions, so that the kms key can be used for CloudWatch logs.
=> Fix terraform deployment by adding proper kms permissions

backend/Dockerfile, backend/Dockerfile.worker, backend/tools/build-worker.sh
Fix worker build by pinning SHA version of node:14-alpine3.14 container. Our worker build was failing because the node:14-alpine3.14 container was recently updated. This PR follows the approach in https://rockbag.medium.com/why-you-should-pin-your-docker-images-with-sha-instead-of-tags-fd132443b8a6 to pin the version of the Docker container used.
=> Fix worker build by using new versions of packages

.github/workflows/backend.yml, backend/src/api/docker-events.ts, backend/src/tasks/ecs-client.ts, backend/webpack.backend.config.js
Dynamically import dockerode to fix backend deployment errors.
=> Dynamically import dockerode to fix backend deployment errors

backend/src/tasks/hibp.ts
Fixes #1352 
HIBP is running into issues. We believe this is due to the request library currently being used
HIBP Scan is failing with the following error:
throw new Error('The `onCancel` handler was attached after the promise settled.');
Tested locally, and with current hibp tests
=> Fix hibp request issues

backend/src/models/service.ts
When there are many domains/services, many queries become near unusable. This seems to be due to a missing domain index on the service model, as evidenced by the following query timing:
```
Limit  (cost=1489934.08..1489934.53 rows=15 width=45) (actual time=70529.010..70529.056 rows=15 loops=1)
->  Unique  (cost=1489934.08..1489940.10 rows=200 width=45) (actual time=70529.009..70529.052 rows=15 loops=1)
->  Sort  (cost=1489934.08..1489936.09 rows=802 width=45) (actual time=70529.008..70529.027 rows=253 loops=1)
Sort Key: "distinctAlias".domain_name, "distinctAlias".domain_id
Sort Method: quicksort  Memory: 298kB
->  Subquery Scan on "distinctAlias"  (cost=1489877.35..1489895.39 rows=802 width=45) (actual time=70526.647..70528.037 rows=2585 loops=1)
->  Group  (cost=1489877.35..1489887.37 …
```
=> Add domain index to service

backend/src/tasks/functions.yml, backend/src/tasks/scheduler.ts
- Decrease logging so that scheduler has more meaningful logs
- Increase timeout so scheduler doesn't time out (this caused scans to be missed on prod)
=> Fix scheduler issues

backend/src/tasks/pesyncdb.ts, docs/src/documentation-pages/dev/pe.md
fixes #1406
Decided not to build the database schema in pesyncdb. It will simply be a one off script to create the PE db and then we will run our pg_restore scripts in the accessor instance to populate it with our schema and data.
pe.md describes how to set up the database credentials and how to fetch them for connection.
=> Create pesyncdb and pe.md

.github/workflows/backend.yml
Updated caching step to only look at the root file "package-lock.json", this should probably fix the tests.
Error we got -- https://github.com/cisagov/crossfeed/runs/5426880059?check_suite_focus=true:
=> fix backend workflow

backend/src/tasks/cve.ts
Simplify cve open / closed vulnerability logic. It was pretty confusing to follow the old code's logic, so hopefully this PR makes it much clearer and easier to follow.
=> Simplify cve open / closed vulnerability logic

backend/src/tasks/dnstwist.ts, backend/src/tasks/test/dnstwist.test.ts
fixes #1452
DNSTwist will now run only on root domains instead of all sub-domains. This will increase performance and ensure the database doesn't overload.
=> Adjust dnstwist to run on only root domains

frontend/src/hooks/usePersistentState.ts
Set cookies to be "secure" (remediates one of the WAS findings). For https://github.com/cisagov/crossfeed/issues/1462
=> Set cookies to be "secure"

.github/workflows/backend.yml, .github/workflows/security.yml, backend/Dockerfile.worker, backend/worker/requirements.txt
Upgrade worker dependencies:
- upgrade python because 3.9.15-r0 is no longer available on the alpine image
- upgrade mitmproxy to 9
- upgrade cryptography to 38
=> Upgrade worker deps

frontend/src/pages/AuthLogin/AuthLogin.tsx
Fixes refresh issue in https://github.com/cisagov/crossfeed/issues/1606. Once a user signs in, call refreshUser() so that the callback is called and the user gets signed in.
=> Ensure user sign in works properly and doesn't hang

infrastructure/matomo.tf
=> Disable IAM authentication for matomo db

infrastructure/pe.tf
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-quota.html
There is an EventBridge limit for the amount of targets assigned to a specific CloudWatch rule. P&E has 9 events, so we need to create a second rule. One rule will cover all 4 of the Cybersixgill events (scheduled-pe-event-cybersixgill-rule) and the second will cover the 5 others (scheduled-pe-event-rule).
=> Create a second rule for P&E Cloudwatch events

backend/Dockerfile.worker
Amass is failing in the Dockerfile.worker. I think the old install link has been deprecated in [releases](https://github.com/owasp-amass/amass/releases) .
Upgraded to the latest version. Link below describes the differences.
https://github.com/owasp-amass/amass/compare/v3.7.3...v3.22.2
=> Fix amass install by updating the link

backend/src/api/app.ts
Added pathRewrite to the P&E proxy because the Crossfeed endpoint, /pe, doesn't exist in the P&E app.
Was able to set up both apps locally and get successful results performing this request:
```
url = "http://localhost:3000/pe/apiv1/cidrs"
headers = {
"Authorization": <crossfeed-api-key>,
"Content-Type": "application/orjson",
"access_token": <pe-api-key>,
}
response = requests.post(url, headers=headers)
print(response.text)
```
*localhost:3000 is the REACT_APP_API_URL
=> Fix proxy to P&E API

backend/package-lock.json, backend/package.json, backend/src/tasks/helpers/simple-wappalyzer.ts, backend/src/tasks/test/wappalyzer.test.ts
Handles problems in Issue #1819 by using the local version of technologies.json and replace ts-jest/utils with jest-mock.
Also changes the package and package-lock files to handle needed libraries.
Solves immediate problems of the app not building.  The techonolgies.json file is a possible temporary solution pending a decision on actively concatenating the technologies from wappalyzer.
To fix the broken app.
Tested locally
=> Issue #1819 - fix missing technologies.json file and ts-jest/utils no longer existing

backend/src/api/auth.ts
This isn't really an error because sometimes we call the API anonymously. Removing this log as it clutters the logs
```
backend_1   | JsonWebTokenError: jwt must be provided
backend_1   |     at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:53:17)
backend_1   |     at /app/src/api/auth.ts:211:20
backend_1   |     at step (/app/src/api/auth.ts:33:23)
backend_1   |     at Object.next (/app/src/api/auth.ts:14:53)
backend_1   |     at fulfilled (/app/src/api/auth.ts:5:58)
backend_1   |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
=> Remove extraneous "jwt must be provided" log

docs/src/templates/documentation-page.js
Fixes https://github.com/cisagov/crossfeed/issues/1822. I think it broke with the latest upgrade to gatsby. I used the approach in https://stackoverflow.com/questions/59070216/webpack-file-loader-outputs-object-module to fix it.
=> Fix docs architecture diagram

backend/Dockerfile.worker
Replacing inline the pandas version to skip building the wheel and use the one from base image.
We use sed to replace the current version with one that has a prebuilt wheel in alpine base image. This reduces the build time significantly.
Building the backend.
=> Replacing pandas version

Dockerfile.docs, backend/worker/requirements.txt, docs/package-lock.json, docs/package.json
Removing all vulnerabilities that have an available fix from the Docs image.
Using overrides to address vulnerabilities in dependent packages.
Update base image to address openssl vuln.
The images should be devoid of vulnerabilities.
Testing by building all images. accessing the docs website.
Before fixes:
After the fixes:
=> Fix docs vulns

frontend/src/components/Header.tsx
This update will prevent the user from navigating to a page that doesn't exist on the server. 
If the user is on an an individual organization page selecting one of the organizations in the header dropdown box should navigate the user to the selected organizations individual organization page. 
The issue occurs when a user selects a tag from the list instead of another organization. Crossfeed then routes the user to the /organizations/{id} route that replaces the id with the tag id, but that page doesn't have anything on it yet.  We want to limit the users to only be able to select the organizations from the dropdown. They can still see the tags listed, but if they select it, it will stay on the current organization, but update the context accordingly. So if they go back to the homepage, …
=> ljf - Prevent navigation if the a tag is selected in the header dropdown when on an organization page Fixes 1872 

backend/src/api/reports.ts
Change the Swagger documentation for the two reports API endpoints from `get` to `post` to correctly reflect how they are implemented.
=> Fix reports API documentation

backend/worker/requirements.txt, frontend/Dockerfile, frontend/package-lock.json, frontend/package.json, frontend/src/components/ScanForm/ScanForm.tsx
Fixing frontend vulnerabilities by updating the base image, some packages and provide overrides for some dependencies.
Run apk update upgrade to eliminate openssl vuln in base image.
Upgraded some node packages.
Added some overrides to use version of dependencies that don't have vulns.
Remove vulnerabilities from frontend image.
Access the url on the local host.
=> Fixing frontend image vulnerabilities

infrastructure/database.tf
Turn on Cloudwatch logging for the PostgreSQL database on AWS via Terraform.
Based on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#enabled_cloudwatch_logs_exports
Provide logs
=> Turn on Cloudwatch logging for Postgres

frontend/src/styles.scss
Hiding the error overlay frame in dev mode.
Using css to remove the error overlay in dev mode. The error overlay window/frame was introduced in react-scripts v5 (as a result of upgrade due to vulnerabilities). 
While using react-script there is no way to override the behavior. 
There are some methods to avoid this but they are more involved. (see https://marmelab.com/blog/2021/07/22/cra-webpack-no-eject.html)
The solution implemented is described here:
https://stackoverflow.com/questions/46589819/disable-error-overlay-in-development-mode
The change is required to avoid unnecessary clicks during development work.
A standard user was created and used to log-in. Observe: the overlay error doesn't happen anymore.
=> Hiding the error overlay frame in dev mode.

infrastructure/database.tf
To allow for major_version change in Postgres the statement `allow_major_version_upgrade = true` was added.
This is based on the Terraform documentation at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance .
Allows for the automated database upgrade of Postgres to 14.4.  The Terraform was previously missing the major_upgrade line.
Terraform will not allow for the jump from 11 to 14 without this line.
Tested locally.  Previously upgraded Postgres in the docker-compose file to jump from 11 to 14 and there was no negative effect.
=> Allow Major Version Update of Postgres in Terraform

backend/worker/worker-entry.sh
Added a timeout of 1 day to the containers.  Will limit local Docker scans and AWS Fargate containers to 1 day of running before killing.
Fargate containers are currently running for lengthy periods of time with no graceful (or ungraceful) way to end.  The timeout will now close them after 24 hours.
Tested locally with a variety of times.
1s or 1 second
30s or 30 seconds
10m or 10 minutes
Those with short times on the timeout exit before completing.  Those with a longer period complete as expected.  
- [] Tests have been added and/or modified to cover the changes in this PR.
=> Added timeout for containers / End after 1 day (24 hours)

.github/workflows/frontend.yml
The reason why the frontend deploys weren't working is because `ubuntu-18.04` is no longer supported by GHA as of April 1, 2023, so we need to change it to `ubuntu-latest` -- see https://stackoverflow.com/questions/70959954/error-waiting-for-a-runner-to-pick-up-this-job-using-github-actions.
=> Fix frontend deploy by updating runner for gha

backend/package-lock.json, backend/package.json
Lock elasticsearch version to 7.10.x to fix compatibilty error in syncdb: 
https://github.com/cisagov/crossfeed/actions/runs/5424040124/jobs/9863058526
AWS will not support elasticsearch > 7.10. 
https://aws.amazon.com/what-is/opensearch/#seo-faq-pairs#will-amazon-opensearch-service-support-new-elasticsearch-versions-beyond-7-10
=> Fix syncdb by locking elasticsearch to 7.10.x

backend/package-lock.json, backend/package.json, backend/src/tasks/helpers/simple-wappalyzer.ts, backend/src/tasks/test/wappalyzer.test.ts, backend/src/tasks/wappalyzer.ts, backend/webpack.worker.config.js
Update wappalyzer to latest. 
Add timeout to axios get request.
Run wapplyzer/save results only on successful requests (http 2xx response code). Also update db only when we have technology results.
Remove webpack mock plugin for ws (part of some classes used by jsdom have "ws" in path). Moving canvas to externals.
Refactored logging for wappalyzer.
Deal with different scenarios where the cookie parser may fail.
As of this PR, devs should be able to run wappalyzer scan locally (against real live domains) and have the results in the db.
The production wappalyzer scans fail. From reading through the logs it seems that some jobs do not finish (could be that they timeout). We do see some axios errors that appear on successful runs as well on failed ones.  
All tests pass.
to …
=> Small wappalyzer fixes

frontend/src/components/Header.tsx, frontend/src/components/__tests__/__snapshots__/header.spec.tsx.snap, frontend/src/test-utils/organization.ts, frontend/src/types/organization.ts
Hiding Reports page 
due to no current data being presented needed to hide this page until it gets updated. 
frontend/src/components/Header.tsx
commented out line 250-255 to hide page.
frontend/src/components/Header.tsx
comment out line 250-255 to hide the page.
Will need to uncomment when reports page is finished.
Clients get confused on reports page when nothing is presented currently. 
gives dev team a chance to update the reports page
used local crossed to verify changes 
before when reports page was present to
reports page hide on the nav bar.
=> Updated header (Nav Bar) for hiding reports page

frontend/src/components/Header.tsx, frontend/src/components/__tests__/__snapshots__/header.spec.tsx.snap
Hiding Feeds page
due to no current data being presented needed to hide this page until it gets updated.
frontend/src/components/Header.tsx
commented out line 251-256 to hide page.
Clients get confused on feeds page when nothing is presented currently. 
gives dev team a chance to update the feeds page
used local crossed to verify changes
before feeds page changes were made:
after feeds page became hidden from nav bar:
=> updating the nav bar to hide feeds page until finished

infrastructure/cloudtrail.tf
Enables KMS encryption of our Terraform-managed CloudTrail.
- Add kms_key_id to CloudTrail resource to enable encryption.
- Add CloudTrail kms policy; rename CloudTrail s3 policy.
- Refactor assume_role_policy to use jsonencode() for code readablitiy and IDE error checking.
See issue #2256 
Related to CIS AWS Foundations Benchmark v1.4.0/3.7
=> 2256 encrypt cloudtrail logs

backend/env.yml, backend/src/tasks/scanExecution.ts, backend/src/tasks/test/scanExecution.test.ts
Create test for the scanExecution lambda that is triggered by the SQS Queue.
=> Create test for scanExecution lambda

frontend/src/components/Footer/styleFooter.ts
Page footer currently cuts off "Export Users" section of "Users" page, to include cutting off other pages within crossfeed. User is unable to scroll past footer or page in order to reach export section or cuts off information on other pages.
go to frontend/src/components/footer/styleFooter.ts
Will be using local crossfeed to make and update changes.
=> Footer cutting off bottom of all pages

backend/src/tasks/functions.yml, infrastructure/pe_worker.tf
Creating a new ECS service failed because we didn't set the network configuration. This is required if the task_definition network mode is set to awsvpc.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#network_configuration
=> Add network_configuration to aws_ecs_service (pe-worker-shodan)

backend/serverless.yml
Lambdas need permissions to describe ECS services and send/delete SQS messages in order to run our SQS scanning functions.
=> Add lambda permissions for SQS and ECS

backend/serverless.yml, backend/src/tasks/scanExecution.ts, infrastructure/pe_worker.tf
The pe-staging-worker log group isn't created automatically so need to add this to the terraform.
Another oversight is when the desired count is set to 5, we need to make sure that when all the messages have gone through, we reset the desired count to 0 so that no more fargate tasks run.
=> Add PE worker log group and make sure desired count gets set back to 0

backend/src/api/helpers.ts, backend/src/tasks/s3-client.ts, dev.env.example
=> Issue 2406/add email template s3 logic

frontend/env.yml, frontend/serverless.yml
Remove VPC Endpoints from Serverless Frontend (Not needed with NAT gateway)
Frontend deployent was failing because SSM couldn't find the BACKEND_VPC_ENDPOINT
=> Remove VPC Endpoints from Serverless Frontend

frontend/serverless.yml
Fix this error:
https://github.com/cisagov/crossfeed/actions/runs/7477853608/job/20351662987
Private Rest API's require a resource policy, so add what is being used in the gov cloud (minus the vpc endpoint restriction)
=> Fix Frontend Pipeline: Add resource policy to API Gateway

infrastructure/api_gateway_alarms.tf
Bug that is causing the infrastructure pipeline to fail. See here:
https://github.com/cisagov/crossfeed/actions/runs/7506627532/job/20438453930
Added namespace to failing resource.
=> Add namespace to aws_cloudwatch_metric_alarm

backend/worker/pe-worker-entry.sh
Fix typo: name of the environment variable being passed through the ECS service's task definition is SERVICE_QUEUE_URL instead of QUEUE_URL.
=> Fix ENV variable name in Fargate entry

infrastructure/worker.tf
The Fargate containers need permission to read/write to the SQS queues. 
The right permissions were added to the execution role but also need to be in the task role.
=> Add SQS permissions to Fargate task role

infrastructure/database.tf
Update the code to match AWS RDS version 15.5. The code still had it as 15.3.
=> Update RDS engine to 15.5

backend/serverless.yml
Convert the backend API to regional private. This is how we have it configured in the govcloud, so it is best to keep it consistent. Also, it was an edge-optimized API gateway which requires the use of cloudfront (we no longer want to use).
=> Convert backend API to private

backend/serverless.yml, frontend/serverless.yml
API Gateways need to be Regional instead of PRIVATE in order for it to be reachable. This is just for the staging-cd environment, not the Gov Cloud accounts.
=> Change API Gateways to Regional

backend/worker/generate_config.sh, backend/worker/pe-worker-entry.sh, infrastructure/pe_worker.tf
This PR:
- adds more memory to Fargate tasks to match what Crossfeed had before
- Cleans up logging
- Make sure the desired count isn't changed on deployment
Clean up and small adjustments for SQS workflow.
Passes all pytests and pre-checks.
=> Add more memory to Fargate tasks and cleanup logging

backend/src/api/app.ts, frontend/scripts/constants.js
Add Wildcard to CORS to address errors
Leadership requests adding wildcard to resolve access issues for endpoints and CORS errors
Confirm CORS errors no longer exist in DMZ
=> Add wildcard to CORS origin to fix access issues

backend/env.yml
Need to add PE_API_KEY and CF_API_KEY to env.yml so the Lambda and Fargate tasks have access to the variables from the parameter store.
Failing cveSync and vulnSync scans.
=> Add PE and CF API keys to env.yml
