- backend/tools/deploy-worker.sh
Fix the path of "build-worker.sh".
> Fix worker deploy script

- README.md
- docs/CONTRIBUTING.md
Update and reorganize README:
- Update development setup information
- Add the Crossfeed logo
- Add a short blurb about what Crossfeed does in more detail
- Move development information to CONTRIBUTING.md
Screenshot:
> Update, reorganize README

- .github/workflows/frontend.yml
- frontend/src/pages/Dashboard/Dashboard.tsx
Fixes #214 and current builds.
> Add build to frontend test

- frontend/src/pages/Organizations/Organizations.tsx
Fixes #220 -- it was a regression introduced by the granular scans PR.
> Fix organization creation

- backend/src/models/domain.ts
> Add organization to unique constraint

- backend/Dockerfile.worker
> install nvdtools directly from go

- backend/src/api/users.ts
- backend/src/models/user.ts
- backend/test/users.test.ts
- frontend/src/pages/Organization/Organization.tsx
- Allows updating a user's role by inviting them again (this would previously give a 500)
- Update a user's name now updates their full name.
> Improve updating roles

- frontend/src/pages/Scans/ScanTasksView.tsx
- frontend/src/pages/Scans/ScansView.tsx
- Sort scan tasks by createdAt by default
- Add scan description to scans table
Fixes #250 and #160.
> Scan fixes

- backend/src/api/vulnerabilities.ts
- frontend/src/pages/Domain/Domain.tsx
- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
- frontend/src/pages/Vulnerabilities/columns.tsx
- frontend/src/pages/Vulnerabilities/styles.module.scss
Updates to the vulnerability UI, including linking to the NIST NVD, adding a showAll checkbox/supporting global or single organization view, and showing vulnerabilities under a domain's detail view (to be added).
> Vulnerability ui updates

- backend/src/api/scans.ts
Fixes #264 by marking Wappalyzer as passive and updating some scan descriptions.
> Mark Wappalyzer as passive, update scan descriptions

- backend/serverless.yml
Enables AES256 encryption for serverless's deployment bucket.
> Enable serverless S3 encryption

- backend/package-lock.json
- frontend/package-lock.json
- frontend/package.json
Fixes all 3 identified vulnerabilities in npm dependencies.
> Fix npm vulnerabilities

- backend/src/tasks/bastion.ts
- backend/src/tasks/functions.yml
- backend/src/tasks/makeGlobalAdmin.ts
Fixes #233 by adding a bastion lambda function.
> Add bastion lambda

- frontend/src/pages/Scans/ScanTasksView.tsx
- frontend/src/pages/Scans/Scans.module.scss
This is easier for local debugging, so you don't have to keep expanding & unexpanding the log to view the latest version of the log.
Also, the log will now scroll to the end by default.
> Add refresh button for logs

- backend/src/api/users.ts
- frontend/src/pages/TermsOfUse/TermsOfUse.tsx
This fixes #342, a bug that would make users sign the terms multiple times before continuing.
> Fix terms signing bug

- .github/workflows/frontend.yml
Updates github actions env vars to use cognito for frontend.
> Enable Cognito for frontend

- frontend/src/pages/AuthLogin/AuthLogin.tsx
> Hide "LESS_THAN_TWO_MFA_VALUES_MESSAGE" message

- backend/src/api/users.ts
> Update invite email

- .github/workflows/frontend.yml
This allows us to use cognito in prod.
> Update prod frontend to use cognito

- backend/src/tasks/ecs-client.ts
> Fix cve OOM error by allowing node to use more memory

- backend/src/models/domain.ts
- backend/src/models/service.ts
- backend/src/tasks/cve.ts
- backend/src/tasks/test/wappalyzer.test.ts
- backend/src/tasks/wappalyzer.ts
- frontend/src/components/WebInfo/WebInfo.tsx
- frontend/src/pages/Dashboard/columns.tsx
- frontend/src/pages/Domain/Domain.tsx
- frontend/src/types/domain.ts
This PR fixes #323, #321, and #320 by storing services in a unified format, including with CPEs, and displaying this unified view in the frontend.
> Store services in unified format

- frontend/src/pages/TermsOfUse/TermsOfUse.tsx
> Update terms of use

- backend/env.yml
- frontend/src/pages/Scans/ScanTasksView.tsx
> Fix viewing scan logs in prod

- frontend/src/pages/TermsOfUse/TermsOfUse.tsx
Adds back bypass that we had temporarily removed for testing.
> Bypass ToU for CISA emails

- backend/src/api/auth.ts
> Change session expiration to 1 day

- backend/package-lock.json
- backend/package.json
- backend/src/api/app.ts
- frontend/src/index.tsx
- Add helmet for HSTS
- Use React hydrate instead of render
> Add HSTS to API

- backend/src/api/domains.ts
- backend/src/tasks/cve.ts
- backend/src/tasks/helpers/saveVulnerabilitiesToDb.ts
- Don't update state of vulnerability if already closed
- Don't show closed vulnerabilities
> Fix vuln display

- frontend/src/context/AuthContextProvider.tsx
> Remove unused history call

- .github/workflows/frontend.yml
- backend/env.yml
- docs/contributing/deployment.md
> Add terms version

- frontend/src/pages/Dashboard/Dashboard.tsx
- frontend/src/pages/Dashboard/columns.tsx
- frontend/src/pages/Domain/Domain.tsx
- frontend/src/types/domain.ts
Adds first seen to domain table and individual domain view.
Fixes #523.
> Add first seen to domain view

- backend/src/api/auth.ts
- backend/src/api/vulnerabilities.ts
- backend/test/domains.test.ts
- backend/test/organizations.test.ts
- backend/test/scan-tasks.test.ts
- backend/test/stats.test.ts
- backend/test/users.test.ts
- backend/test/vulnerabilities.test.ts
This PR does a few things:
- Fix bug where organization users could not update a vulnerability state
- Adds test for updating vulnerability state
- Fixes bug where authorization would not check that a user's role was approved
- Adds test where user's role is not approved
Fixes #503
> Fix updating vulnerability state

- frontend/package-lock.json
- frontend/package.json
This causes errors, as described at https://github.com/facebook/create-react-app/issues/9515.
> Revert typescript update

- backend/src/models/service.ts
- frontend/src/components/WebInfo/WebInfo.tsx
This PR makes it so we properly filter out unauthorized services from Intrigue.
> Fix unauthorized service

- .github/workflows/dependabot-automerge.yml
Changes pullRequests to pulls due to breaking changes in Github API.
> Fix automerge

- backend/src/tasks/censysIpv4.ts
- backend/src/tasks/helpers/getAllDomains.ts
- backend/src/tasks/test/helpers/getAllDomains.test.ts
- frontend/src/pages/Scans/ScansView.tsx
This allows us to only run CensysIPv4 on certain organizations.
> Add granular control for Censys

- .github/workflows/dependabot-automerge.yml
See #578 -- we need to resolve that before we can re-add automerge.
> Disable automerge for now

- backend/src/api/vulnerabilities.ts
- backend/src/models/vulnerability.ts
- backend/src/tasks/cve.ts
- backend/src/tasks/test/__snapshots__/cve.test.ts.snap
- backend/src/tasks/test/cve.test.ts
- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
- frontend/src/types/vulnerability.ts
- Automatically close vulnerabilities after a certain period of time not being seen (currently 1 day)
- [todo] Populate vulnerability information from NIST NVD
> CVE Updates

- backend/env.yml
- backend/src/tasks/ecs-client.ts
- dev.env.example
- docs/contributing/deployment.md
- docs/scans.md
Fixes #530. I've set the following SSM variables:
```
/crossfeed/staging/WORKER_USER_AGENT
Mozilla/5.0 (compatible; CISA_Crossfeed_Staging/1.0; +https://docs.crossfeed.cyber.dhs.gov/scans/)
/crossfeed/prod/WORKER_USER_AGENT
Mozilla/5.0 (compatible; CISA_Crossfeed/1.0; +https://docs.crossfeed.cyber.dhs.gov/scans/)
```
> Update user agent and set value using SSM

- frontend/src/components/Header.tsx
- frontend/src/context/AuthContextProvider.tsx
- frontend/src/context/userStateUtils.ts
- frontend/src/pages/Organizations/Organizations.tsx
> Fix admin view and logout

- frontend/src/components/WebInfo/WebInfo.tsx
- frontend/src/pages/Dashboard/columns.tsx
- Only show products in one category on domain detail page, use set to ensure unique names
- Only display products once in list of domain table
> Fix product display

- frontend/src/pages/Dashboard/Dashboard.tsx
Temporary fix for exceeding Lambda response size
> Batch CSV export

- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
Fixes the issue where we can't export large numbers of vulnerabilities.
> Export vulnerabilities in batches

- frontend/src/pages/Scans/MultiSelect.tsx
> Fix z-index of dropdown

- backend/src/api/domains.ts
- backend/src/api/vulnerabilities.ts
- frontend/src/pages/Dashboard/columns.tsx
- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
- Filter by service / vulnerability
- Filter by substate
> Expanded filters

- backend/src/tasks/es-client.ts
Removes unnecessary fields from elasticsearch to fix #650.
> Fix elasticsearch total field limit bug

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Search/Dashboard.tsx
- frontend/src/pages/Search/SearchProvider/SearchProvider.tsx
- frontend/src/pages/Search/SearchProvider/buildRequest.js
- frontend/src/pages/Search/SearchProvider/types.ts
add pagination bar to bottom of search page
ability to navigate through pages of results and set result page size
ensure pagination works with staging data
> add pagination bar to search page

- backend/src/tasks/cve.ts
This should fix the errors we are getting.
> Run cpe2cve in chunks

- backend/src/api/search.ts
- backend/src/api/users.ts
- backend/src/tasks/bastion.ts
- backend/src/tasks/es-client.ts
- frontend/src/components/DomainDetails.tsx
Allows deleting all elasticsearch data from the bastion
Fixes #651
> Add support to bastion for elasticsearch

- frontend/src/components/DomainDetails.tsx
Add a dropdown indicator to accordion expansion for ports and vulnerabilities
Make it clear to user that an accordion panels can be expanded
> add dropdown indicator to accordion

- .github/workflows/backend.yml
Runs syncdb after deploying backend
Fixes #155
> Run syncdb on deploy

- backend/src/api/scans.ts
- backend/src/tasks/intrigue-ident.ts
Trying to fix #678 by doing the following:
- set the buffer size of execSync to the max value possible
- Increase CPU / memory of the intrigueIdent scan
> Fix OOM issues with intrigue-ident

- backend/src/api/vulnerabilities.ts
- frontend/src/components/DomainDetails.tsx
- frontend/src/components/Table/styles.module.scss
- Only show banners to global admins
- Fix cpe search
> Improvements

- backend/src/tasks/cve.ts
- backend/src/tasks/test/cve.test.ts
Vulnerabilities that appear again after a vulnerability has been closed should be reopened.
> Add logic for reopening vulnerabilities

- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
Changes to actually use vulnerability substate when automatically marked.
> Fix vulnerability update language

- frontend/src/components/DomainDetails.tsx
- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
- Show number of days a vulnerability has been open
- Show products rather than service for a port
Fixes #708.
> Table updates

- backend/src/api/vulnerabilities.ts
- backend/src/models/vulnerability.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
- frontend/src/types/vulnerability.ts
Allows commenting on vulnerabilities with markdown, fixes #662.
> Add commenting system

- frontend/src/components/SearchBar.tsx
- frontend/src/components/__tests__/__snapshots__/searchBar.spec.tsx.snap
This makes the searching experience much smoother, and brings it in line with something like Censys Search.
> Require user to press "enter" to search; don't search automatically when typing

- backend/src/api/users.ts
- frontend/src/pages/AuthLogin/AuthLogin.tsx
> Fix title for "reset password" code textbox

- frontend/src/App.tsx
> Completely disable matomo frontend

- infrastructure/stage.tfvars
See https://aws.amazon.com/elasticsearch-service/pricing/
> Scale staging to t3.small (same price as t2.small)

- backend/src/tasks/es-client.ts
Less load on elasticsearch cluster when indexing
> Change refreshInterval to 1800s (30 min)

- backend/src/api/scans.ts
- backend/src/tasks/helpers/getLiveWebsites.ts
- backend/src/tasks/webscraper.ts
- frontend/src/pages/Scans/ScansView.tsx
> Run webscraper in chunks to limit elasticsearch insert concurrency

- frontend/src/components/DomainDetails.tsx
- frontend/src/pages/Search/ResultCard.tsx
whole card clickable, format dates in difference in days
> small ui changes

- frontend/src/components/ScanForm/ScanForm.tsx
> Scan Edit - make "Return to scans" button outlined

- backend/src/tasks/test/__snapshots__/cve.test.ts.snap
> Push prod (fix tests)

- frontend/src/components/DomainDetails.tsx
> Fix negative days

- backend/src/api/stats.ts
- backend/test/__snapshots__/stats.test.ts.snap
- backend/test/stats.test.ts
- frontend/src/pages/Risk/Risk.tsx
- Allow clicking items in map
- Fix broken links
Fixes #832
> Risk dashboard improvements

- frontend/src/components/NoResults.tsx
- frontend/src/components/Table/Table.tsx
- frontend/src/context/SearchProvider/buildState.js
- frontend/src/context/SearchProvider/types.ts
- frontend/src/pages/Feeds/Feeds.tsx
- frontend/src/pages/Risk/Risk.tsx
- frontend/src/pages/Search/Dashboard.tsx
- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
Shows a message when no search results, vulnerabilities, or saved searches are found.
We can add the crossfeed icon when that is ready.
> Show messages when no results are found

- backend/src/api/saved-searches.ts
- backend/test/saved-searches.test.ts
- frontend/src/pages/Search/Dashboard.tsx
- frontend/src/types/saved-search.ts
- Don't show all searches to admins
- Fix bug editing vulnerability title
> Saved search improvements

- frontend/src/components/Subnav.tsx
- frontend/src/pages/Search/Dashboard.tsx
- frontend/src/pages/Search/FilterDrawer.tsx
- frontend/src/pages/Search/ResultCard.tsx
Various search QA fixes:
- Fix sidebar borders
- Add commas to result numbers
- Capitalize fields in cards
- Make cards clickable
> Search QA Fixes

- backend/src/tasks/findomain.ts
- backend/worker/mitmproxy_sign_requests.py
- backend/worker/requirements.txt
Need to test this, but I this this may work.
> Block spyse requests

- backend/env.yml
Should decrease load on the database.
> Change max concurrency from 900 -> 300

- backend/src/tasks/shodan.ts
- frontend/src/pages/Scans/ScanTasksView.tsx
- Add "shodan" to scantasks dropdown
- Remove logging of service to reduce clutter with shodan scan logs (sometimes the service can be a really large JSON object)
> Shodan improvements

- backend/src/api/stats.ts
- backend/src/models/connection.ts
Caches expensive stats queries so that they are only executed once every 15 minutes.
> Add caching to stats

- backend/src/tasks/shodan.ts
This increases the resiliency of the Shodan scan.
> Add retry to shodan

- backend/src/tasks/functions.yml
This will help us run larger database queries with the bastion.
> Increase bastion function timeout to 15 minutes

- backend/src/models/service.ts
- backend/src/models/test/service.test.ts
- backend/src/tasks/test/cve.test.ts
- backend/src/tasks/test/wappalyzer.test.ts
- backend/src/tasks/wappalyzer.ts
- frontend/src/types/domain.ts
Fix the wappalyzer scan so that it utilizes the correct output from the simple-wappalyzer library. Fixes #969.
> Fix wappalyzer scan so it uses correct output

- .github/workflows/backend.yml
- .github/workflows/docs.yml
- .github/workflows/frontend.yml
- backend/src/models/service.ts
- backend/src/models/test/service.test.ts
- backend/src/tasks/cve.ts
- backend/src/tasks/helpers/technologies.json
- backend/src/tasks/test/__snapshots__/cve.test.ts.snap
- backend/src/tasks/test/cve.test.ts
- backend/src/tasks/test/wappalyzer.test.ts
- backend/src/tasks/wappalyzer.ts
- frontend/src/types/domain.ts
> Push to prod

- backend/src/tasks/cve.ts
This will hopefully fix the out-of-memory errors seen in #961.
> Decrease batch size for cve

- docs/src/documentation-pages/contributing/setup.md
> Fix doc typo

- backend/src/tasks/cve.ts
- backend/src/tasks/test/__snapshots__/cve.test.ts.snap
- backend/src/tasks/test/cve.test.ts
Fix malformed cpes when cpe has a trailing colon, fixes #988.
> Fix malformed cpes when cpe has a trailing colon, fixes #988

- frontend/src/hooks/useDomainApi.ts
Fix filtering by tag for domains page -- fixes #996.
> Fix filtering by tag for domains page

- infrastructure/database.tf
- infrastructure/worker.tf
- re-add webscraper bucket, because it wasn't properly modified before
- don't pin engine version in the database, as it can auto-upgrade
> Terraform fixes

- backend/src/tasks/cve.ts
cve scan: Log every cpe for better debugging, esp. for issue https://github.com/cisagov/crossfeed/issues/961.
> cve scan: Log every cpe for better debugging

- frontend/src/pages/Risk/Risk.tsx
Fixes #1013. Fix key issue with Risk dashboard by adding a key to the React fragment component.
> Fix key issue with Risk dashboard

- frontend/src/components/OrganizationList/OrganizationList.tsx
Make "Create new Organization" only visible to GLOBAL_ADMINS, fixes #956
Made the "Create new Organization" GridItem conditional to the user being a GLOBAL_ADMIN.
> Make "Create new Organization" only visible to GLOBAL_ADMINS

- frontend/src/components/Header.tsx
A solution to #919
This is a work around that solves it, but I'm struggling to find the cause of the issue. Used ternary because && operator doesn't work. Open for discussion.
> Sidebar Overview bolded fix

- frontend/src/pages/Organization/Organization.tsx
- frontend/src/pages/Scans/ScansView.tsx
- frontend/src/pages/Settings/Settings.tsx
Change "Never" to "None" for consistency, when no date is specified, for all the tables with date columns.
> Change "Never" to "None" for consistency

- backend/Dockerfile
- backend/package.json
- backend/src/tasks/ecs-client.ts
- backend/src/tasks/webscraper.ts
- package-lock.json
- package.json
Fixed some errors while running the  populate command to populate the db
> Fix typing errors and setup errors on Windows

- README.md
remove file suffix to resolve 404
> update readme, markdown link

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Risk/Risk.tsx
fixes #964
- first step of report generation
- design of pdf and placement of button are open for changes
> Create report exporting functionality from the dashboard #964

- docs/src/components/highlights.js
Fix broken link on the main docs page.
> Fix broken link on the docs

- backend/src/api/vulnerabilities.ts
- backend/test/vulnerabilities.test.ts
- frontend/src/App.tsx
- frontend/src/pages/Vulnerabilities/Vulnerabilities.tsx
- frontend/src/pages/Vulnerabilities/columns.tsx
The grouped vulns view is now accessible at http://localhost/inventory/vulnerabilities/grouped.
> Set up grouped vulns view

- frontend/src/pages/Risk/Risk.tsx
fixes #1079
Added See All (top right) to the 3 Vulnerability Cards:
- Latest Vulns —> /vulnerabilities?sort=createdAt&desc=false
- Most common vulnerabilities —> vulnerabilities/grouped
- Open vulnerabilities —> /vulnerabilities
> B1 - Links to Upper right on cards

- backend/Dockerfile.worker
Fixes dockerfile build -- it was broken by https://github.com/rbenv/rbenv-installer/issues/31.
> Fix Dockerfile build

- frontend/src/pages/Risk/Risk.tsx
fixes #1116
Removed map charts from pdf, made it one page, and added loading on page freeze. Also, made small adjustments to Risk card css (card sizes and bottom line of "most common vulns/latest vulns).
> Report generation improvements

- backend/src/api/scans.ts
- backend/src/models/vulnerability.ts
- backend/src/tasks/peDomainSync.ts
- backend/src/tasks/rootDomainSync.ts
- backend/src/tasks/test/rootDomainSync.test.ts
- backend/src/worker.ts
- frontend/src/pages/Scans/ScanTasksView.tsx
Adds domains to the database without running findomain
> Sync pe domains scan

- frontend/package.json
- frontend/src/pages/LoginGovCallback/__tests__/loginGovCallback.spec.tsx
- frontend/src/pages/TermsOfUse/__tests__/termsOfUse.spec.tsx
> fix eslint issues

- frontend/src/pages/Search/ResultCard.tsx
Change the color of Search Results Header to a USWDS blue accent. Fixes #1091 
> Change Color of Results

- frontend/src/components/Header.tsx
- frontend/src/components/__tests__/__snapshots__/header.spec.tsx.snap
Fixes #1108  
Clicked button to verify functionality still exists.
> Moved menu (Hamburger) icon to far right of toolbar

- backend/src/tasks/censysIpv4.ts
- backend/src/tasks/test/censysIpv4.test.ts
fixes https://github.com/cisagov/crossfeed/issues/1180
> Fix censys scan endpoint

- .github/workflows/backend.yml
- .github/workflows/docs.yml
- .github/workflows/frontend.yml
- .github/workflows/security.yml
- backend/src/tasks/censysIpv4.ts
- backend/src/tasks/test/censysIpv4.test.ts
- frontend/src/components/Header.tsx
- frontend/src/components/__tests__/__snapshots__/header.spec.tsx.snap
@dependabot
Bump actions/setup-node from 2.3.2 to 2.4.0 (#1170)
1849152
Commits on Aug 17, 2021
@KeithBonesJr
@aloftus23
Moved menu (Hamburger) icon to far right of toolbar (#1172) …
676d8d3
Commits on Sep 03, 2021
> Deploy prod

- backend/package-lock.json
- backend/package.json
- backend/src/tasks/functions.yml
- backend/src/tasks/pe-data-schema.sql
- backend/src/tasks/pesyncdb.ts
- backend/src/tools/run-pesyncdb.ts
- dev.env.example
- docs/src/documentation-pages/dev/pe.md
P&E database setup using a lambda function called `pesyncdb`. The instructions are here: https://github.com/cisagov/crossfeed/blob/3481a35ddc1dc9d1d32bd109c55e081e6f08afd2/docs/src/documentation-pages/dev/pe.md
> P&E database setup scripts (pesyncdb)

- .github/workflows/infrastructure.yml
- backend/src/api/functions.yml
- deploy-red.sh
- docs/src/documentation-pages/dev/pe.md
- infrastructure/frontend.tf
- infrastructure/provider.tf
- infrastructure/vars.tf
- infrastructure/worker.tf
- package.json
Fix various issues with the COOL deployment so that it works properly from the terraformer instance in the COOL.
Also makes sure that if one deployment command fails, the entire script fails, rather than just continuing to the next line.
> Fix COOL deployment

- docs/src/documentation-pages/dev/pe.md
> Fix PE docs formatting

- backend/src/tasks/dotgov.ts
Update endpoint to scan all dotgov domains.
> Update endpoint to scan all dotgov domains

- backend/src/tasks/dotgov.ts
> Deploy master -> red

- frontend/package-lock.json
- frontend/package.json
> Installed upgraded jspdf package to fix sync test vulnerability

- backend/Dockerfile
- backend/Dockerfile.worker
- docs/Dockerfile
- frontend/Dockerfile
upgrade docker images to 14-bullseye-slim
> upgrade to 14-bullseye-slim

- backend/Dockerfile
- backend/Dockerfile.worker
- docs/Dockerfile
- frontend/Dockerfile
Reverts cisagov/crossfeed#1293
> Revert "upgrade to 14-bullseye-slim"

- backend/src/api/auth.ts
Fixes #1302 
Changed token timeout session from 3 days to 1 day.
> Change Token Timeout Session To 1 day

- .gitignore
- infrastructure/.snyk
- infrastructure/frontend.tf
- infrastructure/matomo.tf
More infra updates and fixes for snyk iac test.
> More infra updates and fixes

- frontend/package-lock.json
- frontend/package.json
upgraded uswds to fix the vulnerability snyk found on the frontend.
> Upgraded USWDS to fix Snyk frontend vulnerability

- backend/src/api/users.ts
Fixes #1321
Updated to reflect requested changes here: https://usdhs.sharepoint.com/:w:/s/CyHyTeamO365/ESS3KA3w2YpLtiJSWysV56kBGFCh7jpJ9w9pp3jU8R1w1Q?e=Z9yaDX
> Update Crossfeed Invitation Email

- frontend/src/pages/Risk/Risk.tsx
Fix typo in Risk page logic -- I think this is what you meant @aloftus23 when you originally wrote this code...?
> Fix typo in Risk page logic

- backend/Dockerfile.worker
Fixes https://github.com/cisagov/crossfeed/issues/1379
> Upgrade findomain to fix scans

- frontend/src/components/Header.tsx
- frontend/src/components/NavItem.tsx
- frontend/src/test-utils/organization.ts
- frontend/src/types/organization.ts
Fixes Issue #1096
On Narrower screens: 
Overview, Inventory, Feeds, and Scans remain in the NAV
My Account, Manage Settings, Manage Users, My Settings, and Logout are in the Hamburger
Hamburger pops out on the right had side instead of left.
> A4 FIGMA - Prioritizing Nav Items

- docs/src/documentation-pages/dev/accessor.md
- docs/src/documentation-pages/dev/own-instance.md
- infrastructure/Makefile
- infrastructure/database.tf
- infrastructure/output.tf
- infrastructure/prod.tfvars
- infrastructure/ssm-agent-install.sh
- infrastructure/stage.tfvars
- infrastructure/vars.tf
Add accessor instance -- needed for P&E's needs.
> Add accessor instance

- backend/Dockerfile.worker
Worker build is failing: see https://github.com/cisagov/crossfeed/runs/6038733426?check_suite_focus=true
> fix worker build

- backend/worker/pe_scripts/sixgill/redact.py
- backend/worker/pe_scripts/sixgill/run_cybersixgill.py
Redact function was failing on certain drivers license detectors, this PR makes adjustments to the regex and a libraries used to correctly redact all unique US drivers license
We don't want to store pii in our database so this is an important check to ensure it is redacted before entering our db
> Update redact function

- infrastructure/database.tf
Staging instance keeps crashing, optimizing and restarting. This change should limit the these occurrences.
> Increase allocated and max allocated storage in staging instance

- infrastructure/frontend.tf
> Fix terraform security headers config

- infrastructure/prod.tfvars
Create accessor in production environment by updating prod.tfvars
> Update production to create accessor

- frontend/src/pages/Organization/Organization.tsx
Allow adding multiple root domains / IP blocks by adding commas to separate entries. Fixes https://github.com/cisagov/crossfeed/issues/1483
> Bulk add root domains / IP blocks to organizations

- frontend/src/components/Header.tsx
When the user changes the active organization in the navbar and is on an organization page, navigate them to the organization page that they selected.
When on the organization page, users might expect to be able to change the organization they're viewing from the navbar. This change ensures we match users' expectations.
* Go to an organization's page. Choose a different organization in the navbar (see screenshot below). The organization page should be updated to that of the chosen org.
* Go to a non-organization page on Crossfeed. Choose a different organization in the navbar. You should not be redirected to the organization page of the chosen org.
> Update active organization page from navbar (closes #918)

- .github/dependabot.yml
> Only include major dependabot updates

- frontend/src/components/Header.tsx
As described in #1635, there was a navigation bar issue causing the logo to shrink more than desired with smaller window ratios. This also caused active links in the header to overlap when shrinking the window as well
Change needed to correct nav-bar scaling. It solves the problem of the disappearing logo and overlapping nav items. 
1. Resize window to a tall-thin ratio until the logo and nav-items behave as described. 
Increased the inner width percentage for the header makesStyles function. This aloud the header to retain its size when scaling down the window and stopped the overlapping items.
Before adjustment...
After adjustment...
> Nav-bar scaling with portrait window

- frontend/package-lock.json
> Frontend audit fix vulns

- frontend/package-lock.json
- frontend/package.json
Fix user page crash, fixes https://github.com/cisagov/crossfeed/issues/1689
> Fix user page crash

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/AuthLogin/AuthLogin.tsx
- frontend/src/styles.scss
Fixes https://github.com/cisagov/crossfeed/issues/1606.
Center QR code and make the QR secret hidden:
Also fix the QR code issuer issue by upgrading amplify, see https://github.com/aws-amplify/amplify-ui/issues/3092.
> Fix TOTP issues with aws amplify upgrade

- .github/workflows/docs.yml
- docs/package-lock.json
- docs/package.json
- pin node to 14
- remove netlify-cms-app
- force push to gh-pages to clear out old docs
> Docs fixes

- backend/Dockerfile.worker
- backend/worker/requirements.txt
Upgrade node version on worker to 16.19
> Upgrade node version on worker to 16.19

- .github/workflows/docs.yml
- docs/package-lock.json
- docs/package.json
Reverts cisagov/crossfeed#1710
> Revert "Docs fixes"

- .github/workflows/docs.yml
- docs/package-lock.json
- docs/package.json
Reverts cisagov/crossfeed#1714
> Revert "Revert "Docs fixes""

- backend/package-lock.json
- backend/src/api/app.ts
- backend/src/api/auth.ts
- backend/src/api/login-gov.ts
Fixed major issue that was causing https://github.com/cisagov/crossfeed/issues/1741:
- Properly catch errors when login gov api key is malformed json
Also added some miscellaneous improvements:
- Don't bundle scheduler and docker-events with lambda app
- Clean up login.gov code
> Fix backend

- frontend/src/pages/Risk/Risk.tsx
Added the optional statement to the user variable for writing their name at the bottom of the generated PDF.
Will fix issue with the staging build.
> added optional statement (?) to user variable

- backend/src/api/organizations.ts
Organization names will now sort in an ascending manner (A-Z) for human readability on /organizations.
For usability the names of organization will now sort in an ascending manner when accessing them in /organizations.
Usability
Tested locally
> Sort Organization Names ASC (A-Z) for Readability

- backend/src/api/stats.ts
Adding the limiting clause to the query to prevent PostgreSQL from determining stats for the entire database.  Just the top N, which is currently set to 50, will be returned after this change.
The main overview page on the production version of Crossfeed is taking ~26 seconds or more to render because it is calculating the stats for all entries in the PostgreSQL database.  These ~10,471 results (as of 2023-04-06) are calculated and fully returned in the JSON response from the API but only 5 or so are rendered on the page.
Improve the performance of the main page.  It's taking to long to render and this will cause user's to not use/trust the page.
Tested locally and verified that the full functionality of the website remains.
Accessed all pages of the application in production and observed …
> Added limit in query to account for slow rendering of data

- docs/src/documentation-pages/dev/quickstart.md
Based on @colin-tim 's changes in https://github.com/cisagov/crossfeed/pull/1792
> Change node 14 -> 18 in docs

- frontend/src/components/Header.tsx
Update the org select dropdown to center it vertically. It's possible there's a more elegant solution, but this appears to work.
Before:
After:
> Fix org select dropdown centering

- backend/src/api/auth.ts
Previously there is a jwt error that happens in the backend that causes some issues that have started producing an overlay on the frontend.  We decided to suppress this error message until we decide to go another direction. 
Closes 1922
Manual testing:
Go to login screen and check terminal that npm start is run for error. There shouldn't be showing jwt Error randomly.
> JWT error showing in backend incorrectly. Added additional check in catch statement to filter out jwt Error Fixes 1922

- backend/worker/requirements.txt
- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ScanForm/ScanForm.tsx
- frontend/src/context/AuthContextProvider.tsx
Fixing frontend vulnerabilities by updating the base image, some packages and provide overrides for some dependencies.
Re-submit the original change with a fix for the error overlay showing up on login page (Thank you Matt and Louis). 
Run apk update upgrade to eliminate openssl vuln in base image.
Upgraded some node packages.
Added some overrides to use version of dependencies that don't have vulns.
Remove vulnerabilities from frontend image.
Access the url on the localhost.
> Fixing frontend image vulnerabilities

- backend/worker/requirements.txt
Update requirements to include dnstwist=20230509
1. Add CISA to mock Organization table with cisa.gov as root domain
2. Run single scan limited to CISA
3. Confirm results populate to Vulnerability table
> Add current version of dnstwist.

- frontend/src/components/ScanForm/ScanForm.tsx
See issue #1924 
Closes issue #1924 
The Scans page now displays 1 day as the default scan frequency and minute is no longer an option.
> Set default scan frequency to 1 day; remove Minute(s) option.

- backend/src/api/domains.ts
Replace andHaving statements with andWhere equivalents. Filtering by port, service, and/or vulnerability fields now properly updates the number of results and number of pages.
Closes issue#1636
Navigate to Inventory -> All Domains
Confirm that each column properly filters and updates number of pages/results.
> Fix filtering/pagination for port, service, and vulnerability.

- docker-compose.yml
- infrastructure/matomo.tf
Upgrading matomo to higher version.
Downgrading maria-db to a version suported by aws to avoid staging/prod deployment failures.
Upgrading matomo to reduce the vulnerabilities.
Fix deployment of maria-db in staging/prod.
Deployment and running local tests.
> Matomo upgrade

- backend/src/models/api-key.ts
> Revert hashedKey column type to resolve syncdb error.

- backend/src/models/api-key.ts
Circumvents issue with syncdb attempting to add a new column instead of altering an existing one when column type is changed.
All columns that had a type change have been reverted: api_key.hashedKey and api_key.lastFour.
> 1960 revert lastFour column type

- backend/src/models/domain.ts
- backend/src/models/organization-tag.ts
- backend/src/models/organization.ts
- backend/src/models/saved-search.ts
- backend/src/models/scan.ts
- backend/src/models/user.ts
- backend/src/models/vulnerability.ts
- backend/src/models/webpage.ts
Setting a length limit for these varchars triggers a bug in our syncdb lambda where it attempts to add new columns instead of altering existing ones. Reverting until this is addressed and relying on frontend length limits to mitigate risk.
> Revert varchar length limits to address alter column issue with syncdb lambda.

- backend/src/tasks/functions.yml
Deployment to prod has been failing with the error below, related to the updateScanStatus rule.
```
CREATE_FAILED: CrossfeedprodupdateScanTaskStatusrule1EventBridgeRule (AWS::Events::Rule)
crossfeed-prod-updateScanTaskStatus-rule-1 already exists
```
This PR addresses the error by specifying a new name for the rule. This is a low risk alternative to deleting the rule manually in AWS
> Manually specify name for updateScanStatus rule to bypass CREATE_FAILED error.

- infrastructure/database.tf
Fixes terraform apply errors related to custom parameter group.
> Remove parameter group for postgres 15.

- infrastructure/database.tf
Closes issue #2038. Adds stage to parameter group name.
This prevents terraform apply from failing when staging and prod each attempt to create a db parameter group with the same name.
> Add stage to parameter group to fix terraform apply error.

- docker-compose.yml
- infrastructure/database.tf
Upgrades postgres to latest version, 15.3. Closes issue #2027 
> Upgrade to postgres 15 prod

- infrastructure/database.tf
Sets lifecycle: create_before_destroy = true.
This is needed to change the name of the staging parameter group.
[See Terraform documentation for further information.](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group#create_before_destroy-lifecycle-configuration)
Staging's infrastructure pipeline will fail to build without this change.
Closes issue #2044 
> Add lifecycle config; needed for staging's infrastructure pipeline (allows renaming of parameter group).

- docs/src/pages/search.js
We need to disable the search functionality we don't use so we can prevent any issues.
We had a vulnerability related to XSS attacks that needed to be handled. This fix will ensure that the functionality of the search page is removed and cannot be exploited.
I have commented out the majority of the code, to be put back if we want to enable the search feature that we are presently not using.
navigate to localhost:4000/search and see the blank screen instead of any text.
> Remove functionality we don't use in search.js

- backend/env.yml
- infrastructure/main.tf
Follow up to https://github.com/cisagov/crossfeed/pull/2125
> Update staging API domain in terraform

- backend/package-lock.json
- backend/src/tasks/helpers/technologies.json
- frontend/src/context/userStateUtils.ts
- frontend/src/pages/Feeds/Feeds.tsx
- frontend/src/pages/Feeds/style.ts
Separated logic into separate files specifically with regards to styles. Moved logic of userLevel into separate more relevant file. Removing inline styling.
readability and maintenance QOL 
built from scratch, no errors, feeds working.
- [N/A] *All* future TODOs are captured in issues, which are referenced
- [N/A] All relevant type-of-change labels have been added.
- [N/A] All relevant repo and/or project documentation has been updated
- [N/A] Tests have been added and/or modified to cover the changes in this PR.
> Ticket #2127 Refactoring Feeds

- infrastructure/cloudtrail.tf
- infrastructure/vars.tf
> 2118 au 05 audit process migrate logs to s3 buckets

- infrastructure/database.tf
- infrastructure/elastic.tf
- infrastructure/prod.tfvars
- infrastructure/stage.tfvars
- infrastructure/vars.tf
Update AMI ID for LZ infrastructure -- updating per results of the security scan.
> Update AMI ID for LZ infrastructure

- backend/serverless.yml
> Remove extra commas from logs permissions.

- docs/package-lock.json
- frontend/package-lock.json
Addresses medium vulnerabilities in docs and frontend checks by GitHub Actions. These are preventing deployment.
Closes issue #2275. Closes issue #2276 . 
> Fix medium vulnerabilities flagged by GitHub Actions

- infrastructure/cloudtrail_bucket_policy.tpl
- infrastructure/cloudwatch.tf
- infrastructure/database.tf
- infrastructure/frontend_bucket_policy.tpl
- infrastructure/main.tf
- infrastructure/worker.tf
Adds "Principal": "*" to S3 policy that denies non-SSL requests.
Fixes error preventing infrastructure deployment of PR #2269.
> 2267 s3 buckets should deny non ssl requests

- backend/src/tasks/scanExecution.ts
Add more logging to the scanExecution lambda for debugging and make sure that the Handler is being passed correctly
> Add handler and more logging to the SQS lambda

- backend/src/tasks/scanExecution.ts
- backend/worker/shodan.sh
Don't need to send response back. Will cause recursive runs of lambda. Also add a shodan bash script to run based on a specific message.
> Remove response message in SQS lambda and add Shodan test

- backend/src/tasks/cloudwatchToS3.ts
Refactor lambda to export all log groups (not just those with ExportToS3 tag); refactor variable names for consistency with project.
CloudWatch logs were not being exported to S3 because the cloudwatchToS3 lambda was coded to only log groups with a ExportToS3 tag. Since we intend to export all log groups I removed the code to check for the tag (as opposed to adding the tag to every log group).
> Fix cloudwatchToS3 Lambda

- backend/serverless.yml
- backend/src/tasks/cloudwatchToS3.ts
Add permissions to lambda role so that it can create log export tasks and log streams. This allows the lambda to write logs from CloudWatch to an S3 bucket.
I also removed a redundant permission, logs:GetLogEvent, since this would be covered by logs:Get* on line 75.
> Cloudwatch to s3 lambda: Add log export/stream permissions to lambda role

- backend/serverless.yml
- backend/src/tasks/cloudwatchToS3.ts
- infrastructure/cloudwatch.tf
Refactor lambdas to export based on stage tag: staging lambda will export staging logs, prod lambda will export prod logs, and log groups without a tag will not be exported.
Rename command response variables for code readability.
Increase delay between exports to 30 seconds.
Lambda exports all logs independent of stage. LimitExceededException means lambda is creating a new export task before the last one is finished.
> Cloudwatch to s3 lambda

- frontend/package-lock.json
Bump @babel/traverse 7.22.11 -> 7.23.2 and its dependencies.
- @babel/generator 7.22.10 -> 7.23.0
- @babel/helper-environment-visitor 7.22.5 -> 7.22.20
- @babel/helper-function-name 7.22.5 -> 7.23.0
- @babel/helper-validator-identifier 7.22.5 -> 7.22.20
- @babel/parser 7.22.13 -> 7.23.0
- @babel/template 7.22.5 -> 7.22.15
- @babel/types 7.22.11 -> 7.23.0
@babel/traverse 7.22.11 has a critical vulnerability (See https://github.com/advisories/GHSA-67hx-6x53-jw92).
GitHub Actions is failing because of this node module.
Closes issue #2312 
All tests pass; site functions as expected.
> Bump @babel/traverse to 7.23.2

- frontend/src/pages/AuthLogin/AuthLogin.tsx
Take out brackets around link and fix URL in the temporary notice banner
> Temporary Notice: Take out brackets around link and fix URL

- frontend/src/pages/AuthLogin/AuthLogin.tsx
- frontend/src/styles.scss
> Add notification pane.

- frontend/src/pages/AuthLogin/AuthLogin.tsx
> fix banner.

- frontend/src/pages/AuthLogin/AuthLogin.tsx
Remove extra text in notification banner.
> Fix typos in Notice banner - prod

- frontend/package-lock.json
- frontend/src/pages/AuthLogin/AuthLogin.tsx
updated the warning banner and deleted the migration information within the 1st paragraph.
> Warning Banner text update 

- frontend/src/test-utils/test-utils.tsx
Closes issue #2349.
Address GitHub Actions warning that appears in all PRs.
> Remove unused props import.

- backend/package-lock.json
- docs/package-lock.json
- frontend/package-lock.json
- package-lock.json
This fixes issues found when running `npm audit`. Upon merging this branch, running 'npm audit' should return 0 vulnerabilities at this time. Resolves #2327 
This is required to resolve vulnerabilities found in imported npm packages. 
> Add NPM Vulnerabilities fix to project

- infrastructure/database.tf
- infrastructure/elastic.tf
Add display names to EC2 instances by adding "Name" tag.
See [stack overflow answer here](https://stackoverflow.com/questions/72748192/assign-aws-name-identification-to-an-ec2-instance-using-terraform) and [Terraform documentation here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#tags) for info on using tags for setting display name.
Closes issue #2346 
> Add Name to EC2 instances.

- backend/env.yml
SQS workerQueue no longer exists so remove all references.
Last reference was in the Serverless env.yml which is no longer in use.
> SQS workerQueue no longer exists so remove all references

- infrastructure/log_alarms.tf
> Change Alarm Statistic: SampleCount to Sum.

- backend/Dockerfile.pe
Worker container for P&E was missing the worker directory so couldn't run startup script.
> Add worker directory to the P&E worker container

- infrastructure/sns.tf
See [Terraform docs here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic).
Closes issue #2391 
> Add SSE to sns topic.

- backend/env.yml
Add email_bucket_name to list of environment variables.
> Add email_bucket_name to env.yml

- backend/src/api/helpers.ts
Debugging HTML emails not being delivered, revert to text email.
> Testing SES email delivery system by reverting to text based email

- backend/src/api/helpers.ts
- backend/src/api/users.ts
Adding new email functions for basic testing of text and html formats.
part of #2380 
Testing User registration email notification process.
Verify email is sent on registration signup.
> Add basic text and html email logic to user registration

- backend/.snyk
- backend/worker/.safety-policy.yml
Update safetycli and snyk policy files to suppress vulnerability in scrapy >= 0.7. There is no fix for this vulnerability and it seems we aren't using the vulnerable functions.
Closes issue #2430 
> Set snyk and safety to suppress scrapy vulnerability until 2024-06-01.

- frontend/src/context/Theme.tsx
- frontend/src/pages/Vulnerability/Vulnerability.tsx
Merge this PR into the lz-infra branch: https://github.com/cisagov/crossfeed/pull/2335
> Fix Vuln Details Page in LZ

- frontend/package-lock.json
- frontend/package.json
This addresses the failing frontend tests.
Re-add moduleNameMapper to package.json so jest can handle Axios import statements.
Re-add jest-date-mock to dev dependencies to address failing test.
Re-bump aws-amplify 5.0.4 -> 5.3.12
Closes issue #2445 
> Fix Failing GitHub Actions Check for Frontend Test

- backend/package-lock.json
Resolves #2501 and fixes failed nodemailer backend vulnerabilty check in CI.
Ran npm audit in backend for nodemailer package.
Failed CI checks.
Backend CI pipeline checks should all run sucessfully.
> Update nodemailer to fix CI backend vulnerability failures

- backend/src/api/users.ts
- frontend/src/pages/Users/Users.tsx
Modify getResults in backend/src/api/users.ts to include roles and organization relations.
This fixes the Organizations column on the Users page as well as the Export Users functionality.
Closes issues #2229 
> Fix Export Users

- backend/src/api/users.ts
- frontend/src/pages/Users/Users.tsx
update user import to include state and add region Id
Add state to import user to allow regions to be assigned when bulk importing users
This will allow us to preserve state and region when importing regions
locally tested
> Update user import export to include state

- frontend/src/pages/AuthLogin/AuthLoginCreate.tsx
closes #2531  Adds create-account tab back to AuthLoginCreate.tsx
This needs to be in place to complete registration.
Hitting /registration should show "create-account" tab in login form.
> Add create account tab back to AuthLoginCreate.tsx

- backend/src/api/users.ts
Part of #2508 - Update paths and proper templates 
Fixes registration html emails after static from S3 Bucket transition.
Confirm Registration sends proper email.
> Update registration html template path references

- .github/workflows/frontend.yml
Testing deploy_staging logic in frontend workflow.
> Test workflow if statement for frontend deploy_staging.

- backend/src/api/scans.ts
- backend/src/tasks/helpers/saveDomainsReturn.ts
- backend/src/tasks/test/vuln-sync.test.ts
- backend/src/tasks/vuln-sync.ts
- backend/src/worker.ts
Recommit universal pull of DMZ vulns
Recreate universal pull of DMZ vulns to retrigger the deployment process.
Mirrors PR #2507 
> Recommit universal pull

- .github/workflows/frontend.yml
Reverts cisagov/crossfeed#2569
> Revert "Test workflow if statement for frontend deploy_staging."

- backend/src/api/app.ts
- backend/src/api/organizations.ts
- frontend/scripts/constants.js
Updates express cors origin option to account for crossfeed subdomains such as staging-cd.crossfeed.cyber.dhs.gov/
`[/crossfeed\.cyber\.dhs\.gov$/, /localhost$/]` -> 
`[/.*crossfeed\.cyber\.dhs\.gov$/, /localhost$/]`
> Update Access-Control-Allow-Origin to include subdomains

- backend/src/api/app.ts
- frontend/scripts/constants.js
> Hardcode access-control-allow-origin sites.

- frontend/src/components/OrganizationList/OrganizationList.tsx
Fixes the organization list not populating in DMZ
Org list in DMZ not populating
Check /organizations for population. Should be filtered by regionId of user
> Update organizations list to filter by users regionId

- frontend/src/App.tsx
Fixes Frontend Route permissions for standard user
Standard user does not have some access that is required and logs the user out as unauthorized access.
Access nav links in standard user dashboard without triggering a logout.
> Update route permissions in frontend/src/App.tsx

- frontend/src/components/OrganizationList/OrganizationList.tsx
Update Organizations in frontend to use new /v2/organizations endpoint
Organizations were currently filtered by regionId. Leadership requests access to see all orgs.
Navigation to /organizations in the frontend should show all orgs
> Update get orgs endpoint call to v2 in frontend OrganizationList.tsx

- backend/src/api/app.ts
- frontend/scripts/constants.js
Changes allowed origin from array to single wildcard element.
> Fix CORS formatting.

- frontend/src/components/Header.tsx
- frontend/src/pages/Organizations/Organizations.tsx
Updates Headers.tsx organizations dropdown
Dropdown is broken at old endpoint
Confirm org dropdown exists in header as globalAdmin user.
> Update orgs endpoint to v2 in Header.tsx dropdown
